import '../models/laptop.dart';

// ============================================================
//  LAPTOPHARBOUR PREMIUM FLEET DATABASE
// ============================================================
final List<Laptop> mockLaptops = [

  // ==================== APPLE ====================
  Laptop(
    id: 'apple_01',
    name: 'MacBook Pro 16 M3 Max',
    brand: 'Apple',
    basePrice: 3499.00,
    imageUrl: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=800&auto=format&fit=crop&q=80',
    category: 'Creators',
    rating: 4.95,
    reviewsCount: 312,
    cpu: 'Apple M3 Max (16-Core)',
    gpu: '40-Core GPU',
    ram: '48GB Unified Memory',
    storage: '1TB SSD',
    display: '16.2" Liquid Retina XDR 3456×2234 120Hz',
    battery: '100Wh – up to 22 hours',
    weight: 2.16,
    description: 'The most powerful MacBook Pro ever. M3 Max chip blazes through 8K video timelines, ML training, and massive Xcode builds while staying whisper-quiet with its fanless‑feel Unified Architecture.',
    gamingScore: 78, codingScore: 100, productivityScore: 100, batteryScore: 99,
    cpuOptions: [
      ConfigOption(name: 'M3 Max 14-Core CPU / 30-Core GPU', priceDelta: -400.0),
      ConfigOption(name: 'M3 Max 16-Core CPU / 40-Core GPU', priceDelta: 0.0),
    ],
    gpuOptions: [ConfigOption(name: 'Integrated Apple GPU', priceDelta: 0.0)],
    ramOptions: [
      ConfigOption(name: '36GB Unified Memory', priceDelta: -200.0),
      ConfigOption(name: '48GB Unified Memory', priceDelta: 0.0),
      ConfigOption(name: '96GB Unified Memory', priceDelta: 600.0),
      ConfigOption(name: '128GB Unified Memory', priceDelta: 1000.0),
    ],
    storageOptions: [
      ConfigOption(name: '1TB SSD', priceDelta: 0.0),
      ConfigOption(name: '2TB SSD', priceDelta: 400.0),
      ConfigOption(name: '4TB SSD', priceDelta: 1000.0),
      ConfigOption(name: '8TB SSD', priceDelta: 2000.0),
    ],
    reviews: [
      LaptopReview(username: 'DevFlow', rating: 5.0, date: '2026-07-10', comment: 'Docker, 4K editing, Xcode — all flawless. Unreal battery life.'),
      LaptopReview(username: 'Emily R.', rating: 5.0, date: '2026-07-05', comment: 'Space Black finish is stunning. Speaker system is mindblowing.'),
    ],
  ),

  Laptop(
    id: 'apple_02',
    name: 'MacBook Pro 14 M3 Pro',
    brand: 'Apple',
    basePrice: 1999.00,
    imageUrl: 'https://images.unsplash.com/photo-1531297484001-80022131f5a1?w=800&auto=format&fit=crop&q=80',
    category: 'Creators',
    rating: 4.88,
    reviewsCount: 165,
    cpu: 'Apple M3 Pro (12-Core)',
    gpu: '18-Core GPU',
    ram: '18GB Unified Memory',
    storage: '512GB SSD',
    display: '14.2" Liquid Retina XDR 3024×1964 120Hz ProMotion',
    battery: '72.4Wh – up to 18 hours',
    weight: 1.61,
    description: 'The compact powerhouse. M3 Pro delivers pro-grade performance in a ultra-portable 14-inch form factor perfect for developers, designers, and creative professionals on the move.',
    gamingScore: 65, codingScore: 95, productivityScore: 97, batteryScore: 92,
    cpuOptions: [
      ConfigOption(name: 'M3 Pro 11-Core CPU / 14-Core GPU', priceDelta: -200.0),
      ConfigOption(name: 'M3 Pro 12-Core CPU / 18-Core GPU', priceDelta: 0.0),
    ],
    gpuOptions: [ConfigOption(name: 'Integrated Apple GPU', priceDelta: 0.0)],
    ramOptions: [
      ConfigOption(name: '18GB Unified Memory', priceDelta: 0.0),
      ConfigOption(name: '36GB Unified Memory', priceDelta: 400.0),
    ],
    storageOptions: [
      ConfigOption(name: '512GB SSD', priceDelta: 0.0),
      ConfigOption(name: '1TB SSD', priceDelta: 200.0),
      ConfigOption(name: '2TB SSD', priceDelta: 600.0),
    ],
    reviews: [
      LaptopReview(username: 'CreativeStudio', rating: 5.0, date: '2026-07-07', comment: 'Perfect size. Handles Lightroom CC easily without breaking a sweat.'),
    ],
  ),

  Laptop(
    id: 'apple_03',
    name: 'MacBook Air 15 M3',
    brand: 'Apple',
    basePrice: 1299.00,
    imageUrl: 'https://images.unsplash.com/photo-1611186871348-b1ce696e52c9?w=800&auto=format&fit=crop&q=80',
    category: 'Ultra-portable',
    rating: 4.82,
    reviewsCount: 145,
    cpu: 'Apple M3 (8-Core)',
    gpu: '10-Core GPU',
    ram: '16GB Unified Memory',
    storage: '512GB SSD',
    display: '15.3" Liquid Retina 2880×1864',
    battery: '66.5Wh – up to 18 hours',
    weight: 1.51,
    description: 'Incredibly thin, utterly silent. The fanless M3 Air gives you all-day battery and beautiful 15" screen in a chassis so thin it barely exists. Best laptop for students and everyday users.',
    gamingScore: 45, codingScore: 84, productivityScore: 92, batteryScore: 96,
    cpuOptions: [ConfigOption(name: 'Apple M3 8-Core', priceDelta: 0.0)],
    gpuOptions: [
      ConfigOption(name: '10-Core GPU', priceDelta: 0.0),
    ],
    ramOptions: [
      ConfigOption(name: '8GB Unified Memory', priceDelta: -200.0),
      ConfigOption(name: '16GB Unified Memory', priceDelta: 0.0),
      ConfigOption(name: '24GB Unified Memory', priceDelta: 200.0),
    ],
    storageOptions: [
      ConfigOption(name: '256GB SSD', priceDelta: -200.0),
      ConfigOption(name: '512GB SSD', priceDelta: 0.0),
      ConfigOption(name: '1TB SSD', priceDelta: 200.0),
      ConfigOption(name: '2TB SSD', priceDelta: 600.0),
    ],
    reviews: [
      LaptopReview(username: 'JenS', rating: 5.0, date: '2026-06-30', comment: 'Super lightweight, silent, beautiful screen. Gold standard for travel.'),
    ],
  ),

  Laptop(
    id: 'apple_04',
    name: 'MacBook Air 13 M3',
    brand: 'Apple',
    basePrice: 1099.00,
    imageUrl: 'https://images.unsplash.com/photo-1589642380614-4a8c2aaa09c7?w=800&auto=format&fit=crop&q=80',
    category: 'Ultra-portable',
    rating: 4.79,
    reviewsCount: 228,
    cpu: 'Apple M3 (8-Core)',
    gpu: '10-Core GPU',
    ram: '8GB Unified Memory',
    storage: '256GB SSD',
    display: '13.6" Liquid Retina 2560×1664',
    battery: '52.6Wh – up to 18 hours',
    weight: 1.24,
    description: 'The world\'s best-selling laptop, now smarter. Thin, light, and powerful, the M3 Air handles everyday tasks and creative projects with ease in an impossibly slim design.',
    gamingScore: 40, codingScore: 80, productivityScore: 90, batteryScore: 95,
    cpuOptions: [ConfigOption(name: 'Apple M3 8-Core', priceDelta: 0.0)],
    gpuOptions: [ConfigOption(name: '10-Core GPU', priceDelta: 0.0)],
    ramOptions: [
      ConfigOption(name: '8GB Unified Memory', priceDelta: 0.0),
      ConfigOption(name: '16GB Unified Memory', priceDelta: 200.0),
      ConfigOption(name: '24GB Unified Memory', priceDelta: 400.0),
    ],
    storageOptions: [
      ConfigOption(name: '256GB SSD', priceDelta: 0.0),
      ConfigOption(name: '512GB SSD', priceDelta: 200.0),
      ConfigOption(name: '1TB SSD', priceDelta: 400.0),
    ],
    reviews: [
      LaptopReview(username: 'NomadDev', rating: 4.8, date: '2026-07-01', comment: 'This is the perfect laptop for travel. Light as a feather, incredibly fast.'),
    ],
  ),

  Laptop(
    id: 'apple_05',
    name: 'MacBook Pro 16 M4 Max',
    brand: 'Apple',
    basePrice: 4299.00,
    imageUrl: 'https://images.unsplash.com/photo-1496181130204-755241544e35?w=800&auto=format&fit=crop&q=80',
    category: 'Creators',
    rating: 4.98,
    reviewsCount: 87,
    cpu: 'Apple M4 Max (16-Core)',
    gpu: '40-Core GPU',
    ram: '64GB Unified Memory',
    storage: '1TB SSD',
    display: '16.2" Liquid Retina XDR 3456×2234 120Hz Nano-texture',
    battery: '105Wh – up to 24 hours',
    weight: 2.14,
    description: 'Apple\'s pinnacle of computing power. M4 Max redefines what a laptop can do — compile entire Swift frameworks in seconds, edit multi-stream 8K ProRes RAW footage live, and train neural networks without breaking a sweat.',
    gamingScore: 82, codingScore: 100, productivityScore: 100, batteryScore: 100,
    cpuOptions: [
      ConfigOption(name: 'M4 Max 14-Core CPU / 32-Core GPU', priceDelta: -600.0),
      ConfigOption(name: 'M4 Max 16-Core CPU / 40-Core GPU', priceDelta: 0.0),
    ],
    gpuOptions: [ConfigOption(name: 'Integrated Apple GPU', priceDelta: 0.0)],
    ramOptions: [
      ConfigOption(name: '48GB Unified Memory', priceDelta: -400.0),
      ConfigOption(name: '64GB Unified Memory', priceDelta: 0.0),
      ConfigOption(name: '128GB Unified Memory', priceDelta: 1200.0),
    ],
    storageOptions: [
      ConfigOption(name: '1TB SSD', priceDelta: 0.0),
      ConfigOption(name: '2TB SSD', priceDelta: 400.0),
      ConfigOption(name: '4TB SSD', priceDelta: 1000.0),
      ConfigOption(name: '8TB SSD', priceDelta: 2200.0),
    ],
    reviews: [
      LaptopReview(username: 'MLEngineer', rating: 5.0, date: '2026-07-14', comment: 'Model training that used to take 2 hours on my RTX 3090 now takes 20 minutes. Unreal.'),
      LaptopReview(username: 'ProEditor8K', rating: 5.0, date: '2026-07-12', comment: 'Real-time 8K ProRes RAW editing with multiple streams. Nothing else does this.'),
    ],
  ),

  Laptop(
    id: 'apple_06',
    name: 'MacBook Pro 14 M4 Pro',
    brand: 'Apple',
    basePrice: 2499.00,
    imageUrl: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=800&auto=format&fit=crop&q=80',
    category: 'Business',
    rating: 4.91,
    reviewsCount: 53,
    cpu: 'Apple M4 Pro (14-Core)',
    gpu: '20-Core GPU',
    ram: '24GB Unified Memory',
    storage: '512GB SSD',
    display: '14.2" Liquid Retina XDR 3024×1964 120Hz ProMotion',
    battery: '72.4Wh – up to 20 hours',
    weight: 1.55,
    description: 'The executive\'s laptop of choice. M4 Pro delivers desktop-class performance in an impossibly light 14-inch chassis with the best keyboard, trackpad, and display available on any laptop.',
    gamingScore: 68, codingScore: 98, productivityScore: 99, batteryScore: 94,
    cpuOptions: [
      ConfigOption(name: 'M4 Pro 12-Core CPU / 20-Core GPU', priceDelta: 0.0),
      ConfigOption(name: 'M4 Pro 14-Core CPU / 20-Core GPU', priceDelta: 200.0),
    ],
    gpuOptions: [ConfigOption(name: 'Integrated Apple GPU', priceDelta: 0.0)],
    ramOptions: [
      ConfigOption(name: '24GB Unified Memory', priceDelta: 0.0),
      ConfigOption(name: '48GB Unified Memory', priceDelta: 400.0),
    ],
    storageOptions: [
      ConfigOption(name: '512GB SSD', priceDelta: 0.0),
      ConfigOption(name: '1TB SSD', priceDelta: 200.0),
      ConfigOption(name: '2TB SSD', priceDelta: 600.0),
    ],
    reviews: [
      LaptopReview(username: 'TechExec', rating: 5.0, date: '2026-07-10', comment: 'Finally a pro laptop light enough to carry without noticing. Screen is phenomenal.'),
    ],
  ),

  // ==================== RAZER ====================
  Laptop(
    id: 'razer_01',
    name: 'Blade 18 Platinum',
    brand: 'Razer',
    basePrice: 4299.00,
    imageUrl: 'https://images.unsplash.com/photo-1629429408209-1f912961dbd8?w=800&auto=format&fit=crop&q=80',
    category: 'Gaming',
    rating: 4.95,
    reviewsCount: 48,
    cpu: 'Intel Core i9-14900HX',
    gpu: 'NVIDIA RTX 4090 (16GB)',
    ram: '64GB DDR5',
    storage: '4TB NVMe SSD',
    display: '18" QHD+ 2560×1600 300Hz Mini-LED',
    battery: '99.9Wh – up to 4.5 hours',
    weight: 3.1,
    description: 'The ultimate desktop replacement. Razer\'s 18" monster with a full desktop-class RTX 4090, blazing 300Hz Mini-LED display, and CNC machined aluminum chassis. Pure unapologetic power.',
    gamingScore: 100, codingScore: 97, productivityScore: 88, batteryScore: 38,
    cpuOptions: [ConfigOption(name: 'Intel Core i9-14900HX', priceDelta: 0.0)],
    gpuOptions: [
      ConfigOption(name: 'NVIDIA RTX 4080 (12GB)', priceDelta: -600.0),
      ConfigOption(name: 'NVIDIA RTX 4090 (16GB)', priceDelta: 0.0),
    ],
    ramOptions: [
      ConfigOption(name: '32GB DDR5', priceDelta: -200.0),
      ConfigOption(name: '64GB DDR5', priceDelta: 0.0),
    ],
    storageOptions: [
      ConfigOption(name: '2TB NVMe SSD', priceDelta: -200.0),
      ConfigOption(name: '4TB NVMe SSD', priceDelta: 0.0),
    ],
    reviews: [
      LaptopReview(username: 'HardcoreGamer', rating: 5.0, date: '2026-07-12', comment: 'Nothing on the market touches it. Every game at max 4K with 100+ FPS.'),
      LaptopReview(username: 'StreamKing', rating: 4.9, date: '2026-07-08', comment: 'Stream + game + render — handles all three simultaneously. Absolute beast.'),
    ],
  ),

  Laptop(
    id: 'razer_02',
    name: 'Blade 16 Mercury Edition',
    brand: 'Razer',
    basePrice: 3199.00,
    imageUrl: 'https://images.unsplash.com/photo-1603302576837-37561b2e2302?w=800&auto=format&fit=crop&q=80',
    category: 'Creators',
    rating: 4.89,
    reviewsCount: 64,
    cpu: 'Intel Core i9-14900HX',
    gpu: 'NVIDIA RTX 4080 (12GB)',
    ram: '32GB DDR5',
    storage: '2TB PCIe Gen4 SSD',
    display: '16" QHD+ 2560×1600 240Hz OLED',
    battery: '95Wh – up to 6 hours',
    weight: 2.4,
    description: 'Dressed in pristine Mercury White CNC aluminum, this creator powerhouse matches elite desktop performance with an unmatched 240Hz OLED display for the most discerning professional.',
    gamingScore: 98, codingScore: 95, productivityScore: 90, batteryScore: 60,
    cpuOptions: [ConfigOption(name: 'Intel Core i9-14900HX', priceDelta: 0.0)],
    gpuOptions: [
      ConfigOption(name: 'NVIDIA RTX 4080 (12GB)', priceDelta: 0.0),
      ConfigOption(name: 'NVIDIA RTX 4090 (16GB)', priceDelta: 800.0),
    ],
    ramOptions: [
      ConfigOption(name: '32GB DDR5', priceDelta: 0.0),
      ConfigOption(name: '64GB DDR5', priceDelta: 300.0),
    ],
    storageOptions: [
      ConfigOption(name: '2TB PCIe SSD', priceDelta: 0.0),
      ConfigOption(name: '4TB PCIe SSD', priceDelta: 250.0),
    ],
    reviews: [
      LaptopReview(username: 'StudioM', rating: 5.0, date: '2026-06-15', comment: 'Silver finish is immaculate. Perfect for a creative studio environment.'),
    ],
  ),

  Laptop(
    id: 'razer_03',
    name: 'Blade 15 Advanced',
    brand: 'Razer',
    basePrice: 2299.00,
    imageUrl: 'https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=800&auto=format&fit=crop&q=80',
    category: 'Gaming',
    rating: 4.85,
    reviewsCount: 130,
    cpu: 'Intel Core i7-14700H',
    gpu: 'NVIDIA RTX 4070 (8GB)',
    ram: '16GB DDR5',
    storage: '1TB PCIe Gen4 SSD',
    display: '15.6" QHD 2560×1440 240Hz IPS',
    battery: '80Wh – up to 7 hours',
    weight: 2.01,
    description: 'The iconic Razer Blade 15 — a near-perfect balance of portability, performance, and premium aesthetics. Slim aluminum chassis, per-key Chroma RGB, and formidable RTX graphics.',
    gamingScore: 93, codingScore: 89, productivityScore: 86, batteryScore: 66,
    cpuOptions: [
      ConfigOption(name: 'Intel Core i7-14700H', priceDelta: 0.0),
      ConfigOption(name: 'Intel Core i9-14900HX', priceDelta: 300.0),
    ],
    gpuOptions: [
      ConfigOption(name: 'NVIDIA RTX 4060 (8GB)', priceDelta: -300.0),
      ConfigOption(name: 'NVIDIA RTX 4070 (8GB)', priceDelta: 0.0),
      ConfigOption(name: 'NVIDIA RTX 4080 (12GB)', priceDelta: 500.0),
    ],
    ramOptions: [
      ConfigOption(name: '16GB DDR5', priceDelta: 0.0),
      ConfigOption(name: '32GB DDR5', priceDelta: 120.0),
      ConfigOption(name: '64GB DDR5', priceDelta: 280.0),
    ],
    storageOptions: [
      ConfigOption(name: '1TB PCIe SSD', priceDelta: 0.0),
      ConfigOption(name: '2TB PCIe SSD', priceDelta: 100.0),
    ],
    reviews: [
      LaptopReview(username: 'NightOwl', rating: 4.9, date: '2026-07-02', comment: 'The RGB on this thing is magical. Gaming at 240fps is buttery smooth.'),
      LaptopReview(username: 'GameDev99', rating: 4.8, date: '2026-06-20', comment: 'Build quality feels like a machined metal sculpture. Worth every penny.'),
    ],
  ),

  Laptop(
    id: 'razer_04',
    name: 'Blade 14 Stealth',
    brand: 'Razer',
    basePrice: 1999.00,
    imageUrl: 'https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?w=800&auto=format&fit=crop&q=80',
    category: 'Gaming',
    rating: 4.90,
    reviewsCount: 88,
    cpu: 'AMD Ryzen 9 8945HS',
    gpu: 'NVIDIA RTX 4070 (8GB)',
    ram: '16GB DDR5',
    storage: '1TB PCIe Gen4 SSD',
    display: '14" QHD+ 2560×1600 240Hz IPS',
    battery: '68Wh – up to 7 hours',
    weight: 1.64,
    description: 'Ultra-portable gaming perfection. A CNC aluminum chassis packed with a blistering 240Hz display and Ryzen 9 + RTX 4070 ensures fluid gameplay in a chassis that slips into any backpack.',
    gamingScore: 96, codingScore: 90, productivityScore: 85, batteryScore: 65,
    cpuOptions: [ConfigOption(name: 'AMD Ryzen 9 8945HS', priceDelta: 0.0)],
    gpuOptions: [
      ConfigOption(name: 'NVIDIA RTX 4060 (8GB)', priceDelta: -200.0),
      ConfigOption(name: 'NVIDIA RTX 4070 (8GB)', priceDelta: 0.0),
      ConfigOption(name: 'NVIDIA RTX 4080 (12GB)', priceDelta: 600.0),
    ],
    ramOptions: [
      ConfigOption(name: '16GB DDR5', priceDelta: 0.0),
      ConfigOption(name: '32GB DDR5', priceDelta: 120.0),
    ],
    storageOptions: [
      ConfigOption(name: '1TB PCIe Gen4 SSD', priceDelta: 0.0),
      ConfigOption(name: '2TB PCIe Gen4 SSD', priceDelta: 100.0),
    ],
    reviews: [
      LaptopReview(username: 'GamerPro99', rating: 5.0, date: '2026-07-01', comment: 'Cyberpunk at 90fps ultra settings on a 14" laptop. Insane thermals for the size.'),
      LaptopReview(username: 'Dave K.', rating: 4.8, date: '2026-06-25', comment: 'RGB keyboard is gorgeous, trackpad is huge. Very pleased.'),
    ],
  ),

  Laptop(
    id: 'razer_05',
    name: 'Blade Pro 17 Studio',
    brand: 'Razer',
    basePrice: 3799.00,
    imageUrl: 'https://images.unsplash.com/photo-1541807084-5c52b6b3adef?w=800&auto=format&fit=crop&q=80',
    category: 'Creators',
    rating: 4.82,
    reviewsCount: 41,
    cpu: 'Intel Core i9-14900HX',
    gpu: 'NVIDIA RTX 4080 (12GB)',
    ram: '32GB DDR5',
    storage: '2TB NVMe SSD',
    display: '17.3" 4K UHD 3840×2160 144Hz OLED Touch',
    battery: '99.9Wh – up to 5 hours',
    weight: 2.75,
    description: 'The studio powerhouse with a jaw-dropping 4K OLED touchscreen. Colour-accurate display with 100% DCI-P3 coverage and factory calibration makes this the go-to for video editors and 3D artists.',
    gamingScore: 97, codingScore: 94, productivityScore: 93, batteryScore: 50,
    cpuOptions: [ConfigOption(name: 'Intel Core i9-14900HX', priceDelta: 0.0)],
    gpuOptions: [
      ConfigOption(name: 'NVIDIA RTX 4080 (12GB)', priceDelta: 0.0),
      ConfigOption(name: 'NVIDIA RTX 4090 (16GB)', priceDelta: 800.0),
    ],
    ramOptions: [
      ConfigOption(name: '32GB DDR5', priceDelta: 0.0),
      ConfigOption(name: '64GB DDR5', priceDelta: 300.0),
    ],
    storageOptions: [
      ConfigOption(name: '2TB NVMe SSD', priceDelta: 0.0),
      ConfigOption(name: '4TB NVMe SSD', priceDelta: 250.0),
    ],
    reviews: [
      LaptopReview(username: 'PixelArtist', rating: 5.0, date: '2026-06-22', comment: '4K OLED on a laptop is absolutely breathtaking. Colors are insanely accurate.'),
    ],
  ),

  // ==================== ASUS ====================
  Laptop(
    id: 'asus_01',
    name: 'ROG Zephyrus G16 Ultra',
    brand: 'ASUS',
    basePrice: 2799.00,
    imageUrl: 'https://images.unsplash.com/photo-1593642632823-8f785ba67e45?w=800&auto=format&fit=crop&q=80',
    category: 'Gaming',
    rating: 4.92,
    reviewsCount: 118,
    cpu: 'Intel Core i9-14900H',
    gpu: 'NVIDIA RTX 4090 (16GB)',
    ram: '32GB DDR5',
    storage: '2TB PCIe Gen4 SSD',
    display: '16" 2.5K 2560×1600 240Hz ROG Nebula HDR OLED',
    battery: '90Wh – up to 9 hours',
    weight: 1.95,
    description: 'The thinnest and most powerful ROG Zephyrus ever. Nebula HDR OLED display with 240Hz refresh rate, full-powered RTX 4090, and liquid metal cooling all in a remarkably slim premium chassis.',
    gamingScore: 100, codingScore: 96, productivityScore: 90, batteryScore: 74,
    cpuOptions: [
      ConfigOption(name: 'Intel Core i7-14650HX', priceDelta: -300.0),
      ConfigOption(name: 'Intel Core i9-14900H', priceDelta: 0.0),
    ],
    gpuOptions: [
      ConfigOption(name: 'NVIDIA RTX 4070 Ti (12GB)', priceDelta: -400.0),
      ConfigOption(name: 'NVIDIA RTX 4090 (16GB)', priceDelta: 0.0),
    ],
    ramOptions: [
      ConfigOption(name: '16GB DDR5', priceDelta: -100.0),
      ConfigOption(name: '32GB DDR5', priceDelta: 0.0),
      ConfigOption(name: '64GB DDR5', priceDelta: 200.0),
    ],
    storageOptions: [
      ConfigOption(name: '1TB PCIe SSD', priceDelta: -120.0),
      ConfigOption(name: '2TB PCIe SSD', priceDelta: 0.0),
      ConfigOption(name: '4TB PCIe SSD', priceDelta: 280.0),
    ],
    reviews: [
      LaptopReview(username: 'ROGFanatic', rating: 5.0, date: '2026-07-10', comment: 'The OLED HDR display is the best gaming display I have ever seen on a laptop.'),
      LaptopReview(username: 'SlimGamer', rating: 4.8, date: '2026-07-04', comment: 'Can\'t believe how thin it is with a 4090 inside. Remarkable engineering.'),
    ],
  ),

  Laptop(
    id: 'asus_02',
    name: 'ROG Zephyrus G14 OLED',
    brand: 'ASUS',
    basePrice: 1649.00,
    imageUrl: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=800&auto=format&fit=crop&q=80',
    category: 'Gaming',
    rating: 4.75,
    reviewsCount: 96,
    cpu: 'AMD Ryzen 9 8945HS',
    gpu: 'NVIDIA RTX 4070 (8GB)',
    ram: '16GB LPDDR5X',
    storage: '1TB PCIe Gen4 SSD',
    display: '14" 3K 2880×1800 120Hz ROG Nebula OLED',
    battery: '73Wh – up to 8 hours',
    weight: 1.5,
    description: 'Gaming powerhouse in a compact 14-inch form factor. Nebula OLED display provides unmatched visual quality while AMD Ryzen 9 + RTX 4070 keep the competition crushed.',
    gamingScore: 89, codingScore: 91, productivityScore: 88, batteryScore: 82,
    cpuOptions: [ConfigOption(name: 'AMD Ryzen 9 8945HS', priceDelta: 0.0)],
    gpuOptions: [
      ConfigOption(name: 'NVIDIA RTX 4060 (8GB)', priceDelta: -150.0),
      ConfigOption(name: 'NVIDIA RTX 4070 (8GB)', priceDelta: 0.0),
    ],
    ramOptions: [
      ConfigOption(name: '16GB LPDDR5X', priceDelta: 0.0),
      ConfigOption(name: '32GB LPDDR5X', priceDelta: 100.0),
    ],
    storageOptions: [
      ConfigOption(name: '1TB PCIe Gen4 SSD', priceDelta: 0.0),
      ConfigOption(name: '2TB PCIe Gen4 SSD', priceDelta: 90.0),
    ],
    reviews: [
      LaptopReview(username: 'TechVibe', rating: 5.0, date: '2026-07-05', comment: 'Best 14" laptop I\'ve ever owned. Keyboard and screen are phenomenal.'),
    ],
  ),

  Laptop(
    id: 'asus_03',
    name: 'Zenith Pro 16 X Creator',
    brand: 'ASUS',
    basePrice: 2499.00,
    imageUrl: 'https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?w=800&auto=format&fit=crop&q=80',
    category: 'Creators',
    rating: 4.80,
    reviewsCount: 124,
    cpu: 'AMD Ryzen 9 7940HS',
    gpu: 'NVIDIA RTX 4080 (12GB)',
    ram: '32GB DDR5',
    storage: '1TB NVMe SSD',
    display: '16" 3.2K 3200×2000 120Hz OLED Touch',
    battery: '96Wh – up to 10 hours',
    weight: 1.95,
    description: 'Designed for elite creators. Dual-fan liquid metal cooling, immersive 120Hz OLED touchscreen, and RTX studio drivers deliver unmatched content creation performance.',
    gamingScore: 92, codingScore: 98, productivityScore: 95, batteryScore: 78,
    cpuOptions: [
      ConfigOption(name: 'AMD Ryzen 9 7940HS', priceDelta: 0.0),
      ConfigOption(name: 'Intel Core i9-13900H', priceDelta: 150.0),
    ],
    gpuOptions: [
      ConfigOption(name: 'NVIDIA RTX 4070 (8GB)', priceDelta: -250.0),
      ConfigOption(name: 'NVIDIA RTX 4080 (12GB)', priceDelta: 0.0),
      ConfigOption(name: 'NVIDIA RTX 4090 (16GB)', priceDelta: 500.0),
    ],
    ramOptions: [
      ConfigOption(name: '16GB DDR5', priceDelta: -100.0),
      ConfigOption(name: '32GB DDR5', priceDelta: 0.0),
      ConfigOption(name: '64GB DDR5', priceDelta: 200.0),
    ],
    storageOptions: [
      ConfigOption(name: '1TB NVMe SSD', priceDelta: 0.0),
      ConfigOption(name: '2TB NVMe SSD', priceDelta: 120.0),
      ConfigOption(name: '4TB NVMe SSD', priceDelta: 350.0),
    ],
    reviews: [
      LaptopReview(username: 'Alex Carter', rating: 5.0, date: '2026-06-12', comment: 'Stunning OLED screen. Premiere rendering times cut in half. Best creator notebook.'),
      LaptopReview(username: 'Sarah Jenkins', rating: 4.5, date: '2026-05-30', comment: 'Performance is top-tier. The OLED screen is worth every bit of power it uses.'),
    ],
  ),

  Laptop(
    id: 'asus_04',
    name: 'Zenbook DUO OLED 14',
    brand: 'ASUS',
    basePrice: 2099.00,
    imageUrl: 'https://images.unsplash.com/photo-1541807084-5c52b6b3adef?w=800&auto=format&fit=crop&q=80',
    category: 'Creators',
    rating: 4.67,
    reviewsCount: 42,
    cpu: 'Intel Core Ultra 9 185H',
    gpu: 'Intel Arc Graphics',
    ram: '32GB LPDDR5X',
    storage: '2TB NVMe SSD',
    display: 'Dual 14" 3K 2880×1800 120Hz OLED Touch',
    battery: '75Wh – up to 9 hours',
    weight: 1.65,
    description: 'Groundbreaking dual-screen laptop with two 14-inch OLED touchscreens, detachable Bluetooth keyboard, and integrated kickstand for ultimate portable productivity.',
    gamingScore: 60, codingScore: 96, productivityScore: 99, batteryScore: 75,
    cpuOptions: [ConfigOption(name: 'Intel Core Ultra 9 185H', priceDelta: 0.0)],
    gpuOptions: [ConfigOption(name: 'Intel Arc Graphics', priceDelta: 0.0)],
    ramOptions: [ConfigOption(name: '32GB LPDDR5X', priceDelta: 0.0)],
    storageOptions: [ConfigOption(name: '2TB NVMe SSD', priceDelta: 0.0)],
    reviews: [
      LaptopReview(username: 'MultitaskMaster', rating: 5.0, date: '2026-06-11', comment: 'Two full screens on the go is a game-changer for developers.'),
    ],
  ),

  Laptop(
    id: 'asus_05',
    name: 'ROG Strix SCAR 18',
    brand: 'ASUS',
    basePrice: 3299.00,
    imageUrl: 'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?w=800&auto=format&fit=crop&q=80',
    category: 'Gaming',
    rating: 4.88,
    reviewsCount: 77,
    cpu: 'Intel Core i9-14900HX',
    gpu: 'NVIDIA RTX 4090 (16GB)',
    ram: '32GB DDR5',
    storage: '2TB RAID SSD',
    display: '18" QHD+ 2560×1600 240Hz ROG Nebula HDR Mini-LED',
    battery: '90Wh – up to 4 hours',
    weight: 3.1,
    description: 'The ultimate ROG gaming laptop. Massive 18-inch Mini-LED HDR display, liquid metal on CPU, and desktop RTX 4090 with full GPU power. Built for champions.',
    gamingScore: 100, codingScore: 95, productivityScore: 84, batteryScore: 40,
    cpuOptions: [ConfigOption(name: 'Intel Core i9-14900HX', priceDelta: 0.0)],
    gpuOptions: [
      ConfigOption(name: 'NVIDIA RTX 4080 (12GB)', priceDelta: -500.0),
      ConfigOption(name: 'NVIDIA RTX 4090 (16GB)', priceDelta: 0.0),
    ],
    ramOptions: [
      ConfigOption(name: '32GB DDR5', priceDelta: 0.0),
      ConfigOption(name: '64GB DDR5', priceDelta: 200.0),
    ],
    storageOptions: [
      ConfigOption(name: '2TB RAID SSD', priceDelta: 0.0),
      ConfigOption(name: '4TB RAID SSD', priceDelta: 300.0),
    ],
    reviews: [
      LaptopReview(username: 'SCARcommander', rating: 5.0, date: '2026-07-14', comment: 'The Mini-LED HDR is breathtaking for gaming. Nothing rivals the SCAR 18.'),
    ],
  ),

  Laptop(
    id: 'asus_06',
    name: 'Vivobook Pro 16X OLED',
    brand: 'ASUS',
    basePrice: 1399.00,
    imageUrl: 'https://images.unsplash.com/photo-1585076641399-5c06d1b3365f?w=800&auto=format&fit=crop&q=80',
    category: 'Creators',
    rating: 4.60,
    reviewsCount: 59,
    cpu: 'Intel Core i7-13700H',
    gpu: 'NVIDIA RTX 4060 (8GB)',
    ram: '16GB DDR5',
    storage: '1TB NVMe SSD',
    display: '16" 3.2K 3200×2000 120Hz OLED',
    battery: '96Wh – up to 10 hours',
    weight: 2.0,
    description: 'Professional-grade OLED visuals at a mid-tier price point. Nano Edge display, PANTONE validated color accuracy, and RTX 4060 make this the best-value creator laptop on the market.',
    gamingScore: 70, codingScore: 88, productivityScore: 92, batteryScore: 78,
    cpuOptions: [
      ConfigOption(name: 'Intel Core i7-13700H', priceDelta: 0.0),
      ConfigOption(name: 'Intel Core i9-13900H', priceDelta: 150.0),
    ],
    gpuOptions: [
      ConfigOption(name: 'NVIDIA RTX 4060 (8GB)', priceDelta: 0.0),
      ConfigOption(name: 'NVIDIA RTX 4070 (8GB)', priceDelta: 200.0),
    ],
    ramOptions: [
      ConfigOption(name: '16GB DDR5', priceDelta: 0.0),
      ConfigOption(name: '32GB DDR5', priceDelta: 100.0),
    ],
    storageOptions: [
      ConfigOption(name: '1TB NVMe SSD', priceDelta: 0.0),
      ConfigOption(name: '2TB NVMe SSD', priceDelta: 100.0),
    ],
    reviews: [
      LaptopReview(username: 'GraphicDesignAna', rating: 4.6, date: '2026-06-28', comment: 'PANTONE validated screen is a huge plus for design work. Colors are spot on.'),
    ],
  ),

  // ==================== LENOVO ====================
  Laptop(
    id: 'lenovo_01',
    name: 'ThinkPad X1 Carbon Gen 12',
    brand: 'Lenovo',
    basePrice: 1799.00,
    imageUrl: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=800&auto=format&fit=crop&q=80',
    category: 'Business',
    rating: 4.70,
    reviewsCount: 154,
    cpu: 'Intel Core Ultra 7 155H',
    gpu: 'Intel Arc Graphics',
    ram: '16GB LPDDR5X',
    storage: '512GB PCIe NVMe SSD',
    display: '14" 2.8K 2880×1800 120Hz OLED Anti-Glare',
    battery: '57Wh – up to 12 hours',
    weight: 1.09,
    description: 'The pinnacle of business notebooks. Aerospace-grade carbon fiber, 1.09 kg, legendary ThinkPad keyboard, TrackPoint, and robust security with Intel Core Ultra processors.',
    gamingScore: 55, codingScore: 88, productivityScore: 96, batteryScore: 85,
    cpuOptions: [
      ConfigOption(name: 'Intel Core Ultra 5 125H', priceDelta: -150.0),
      ConfigOption(name: 'Intel Core Ultra 7 155H', priceDelta: 0.0),
      ConfigOption(name: 'Intel Core Ultra 9 185H', priceDelta: 250.0),
    ],
    gpuOptions: [ConfigOption(name: 'Intel Arc Graphics', priceDelta: 0.0)],
    ramOptions: [
      ConfigOption(name: '16GB LPDDR5X', priceDelta: 0.0),
      ConfigOption(name: '32GB LPDDR5X', priceDelta: 100.0),
      ConfigOption(name: '64GB LPDDR5X', priceDelta: 250.0),
    ],
    storageOptions: [
      ConfigOption(name: '512GB PCIe SSD', priceDelta: 0.0),
      ConfigOption(name: '1TB PCIe SSD', priceDelta: 80.0),
      ConfigOption(name: '2TB PCIe SSD', priceDelta: 200.0),
    ],
    reviews: [
      LaptopReview(username: 'EnterpriseArchitect', rating: 5.0, date: '2026-04-18', comment: 'Best typing experience available. Super light and indestructible.'),
      LaptopReview(username: 'Nate S.', rating: 4.4, date: '2026-03-29', comment: 'Light, bright OLED, great keyboard. Solid for office work.'),
    ],
  ),

  Laptop(
    id: 'lenovo_02',
    name: 'Legion Pro 7i Gen 9',
    brand: 'Lenovo',
    basePrice: 2199.00,
    imageUrl: 'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?w=800&auto=format&fit=crop&q=80',
    category: 'Gaming',
    rating: 4.81,
    reviewsCount: 110,
    cpu: 'Intel Core i9-14900HX',
    gpu: 'NVIDIA RTX 4080 (12GB)',
    ram: '32GB DDR5',
    storage: '1TB PCIe SSD',
    display: '16" WQXGA 2560×1600 240Hz IPS',
    battery: '99.9Wh – up to 5 hours',
    weight: 2.62,
    description: 'AI-enhanced gaming powerhouse. Full metal chassis, Legion Coldfront cooling system, and desktop-class performance make this the definitive gaming laptop.',
    gamingScore: 97, codingScore: 94, productivityScore: 82, batteryScore: 50,
    cpuOptions: [ConfigOption(name: 'Intel Core i9-14900HX', priceDelta: 0.0)],
    gpuOptions: [
      ConfigOption(name: 'NVIDIA RTX 4080 (12GB)', priceDelta: 0.0),
      ConfigOption(name: 'NVIDIA RTX 4090 (16GB)', priceDelta: 600.0),
    ],
    ramOptions: [
      ConfigOption(name: '32GB DDR5', priceDelta: 0.0),
      ConfigOption(name: '64GB DDR5', priceDelta: 180.0),
    ],
    storageOptions: [
      ConfigOption(name: '1TB PCIe SSD', priceDelta: 0.0),
      ConfigOption(name: '2TB PCIe SSD', priceDelta: 100.0),
    ],
    reviews: [
      LaptopReview(username: 'ProGamerElite', rating: 5.0, date: '2026-05-18', comment: 'Thermals are rock solid under full load. Exceptional build quality.'),
    ],
  ),

  Laptop(
    id: 'lenovo_03',
    name: 'Yoga Slim 7x Copilot+',
    brand: 'Lenovo',
    basePrice: 1199.00,
    imageUrl: 'https://images.unsplash.com/photo-1585076641399-5c06d1b3365f?w=800&auto=format&fit=crop&q=80',
    category: 'Ultra-portable',
    rating: 4.68,
    reviewsCount: 29,
    cpu: 'Snapdragon X Elite X1E-78-100',
    gpu: 'Qualcomm Adreno GPU',
    ram: '16GB LPDDR5X',
    storage: '512GB NVMe SSD',
    display: '14.5" 3K 2944×1840 90Hz PureSight OLED Touch',
    battery: '70Wh – up to 18 hours',
    weight: 1.28,
    description: 'Next-gen Copilot+ PC. Snapdragon X Elite delivers AI-accelerated performance, all-day battery, and zero noise in an impossibly elegant chassis.',
    gamingScore: 40, codingScore: 89, productivityScore: 95, batteryScore: 97,
    cpuOptions: [ConfigOption(name: 'Snapdragon X Elite X1E-78-100', priceDelta: 0.0)],
    gpuOptions: [ConfigOption(name: 'Qualcomm Adreno GPU', priceDelta: 0.0)],
    ramOptions: [
      ConfigOption(name: '16GB LPDDR5X', priceDelta: 0.0),
      ConfigOption(name: '32GB LPDDR5X', priceDelta: 150.0),
    ],
    storageOptions: [
      ConfigOption(name: '512GB NVMe SSD', priceDelta: 0.0),
      ConfigOption(name: '1TB NVMe SSD', priceDelta: 100.0),
    ],
    reviews: [
      LaptopReview(username: 'SnapDev', rating: 4.6, date: '2026-06-28', comment: 'Battery life is incredible. ARM architecture transition is seamless now.'),
    ],
  ),

  Laptop(
    id: 'lenovo_04',
    name: 'ThinkPad X1 Extreme Gen 5',
    brand: 'Lenovo',
    basePrice: 2499.00,
    imageUrl: 'https://images.unsplash.com/photo-1496181130204-755241544e35?w=800&auto=format&fit=crop&q=80',
    category: 'Business',
    rating: 4.74,
    reviewsCount: 88,
    cpu: 'Intel Core i7-12800H',
    gpu: 'NVIDIA RTX 3060 (6GB)',
    ram: '32GB DDR5',
    storage: '1TB PCIe SSD',
    display: '16" WQXGA 2560×1600 165Hz IPS Anti-Glare',
    battery: '90Wh – up to 10 hours',
    weight: 1.81,
    description: 'Business meets raw performance. Premium construction with demanding graphics capabilities for engineers, data scientists, and power users needing both portability and a discrete GPU.',
    gamingScore: 72, codingScore: 92, productivityScore: 94, batteryScore: 80,
    cpuOptions: [
      ConfigOption(name: 'Intel Core i7-12800H', priceDelta: 0.0),
      ConfigOption(name: 'Intel Core i9-12900H', priceDelta: 200.0),
    ],
    gpuOptions: [
      ConfigOption(name: 'NVIDIA RTX 3060 (6GB)', priceDelta: 0.0),
      ConfigOption(name: 'NVIDIA RTX 3070 Ti (8GB)', priceDelta: 300.0),
    ],
    ramOptions: [
      ConfigOption(name: '16GB DDR5', priceDelta: -100.0),
      ConfigOption(name: '32GB DDR5', priceDelta: 0.0),
      ConfigOption(name: '64GB DDR5', priceDelta: 200.0),
    ],
    storageOptions: [
      ConfigOption(name: '1TB PCIe SSD', priceDelta: 0.0),
      ConfigOption(name: '2TB PCIe SSD', priceDelta: 100.0),
    ],
    reviews: [
      LaptopReview(username: 'DataEngineer', rating: 4.7, date: '2026-05-22', comment: 'Best business laptop with dGPU. Handles TensorFlow workloads like a champ.'),
    ],
  ),

  Laptop(
    id: 'lenovo_05',
    name: 'Legion Go Gaming Laptop',
    brand: 'Lenovo',
    basePrice: 1499.00,
    imageUrl: 'https://images.unsplash.com/photo-1504707748692-419802cf939d?w=800&auto=format&fit=crop&q=80',
    category: 'Gaming',
    rating: 4.65,
    reviewsCount: 67,
    cpu: 'AMD Ryzen 7 7745HX',
    gpu: 'NVIDIA RTX 4060 (8GB)',
    ram: '16GB DDR5',
    storage: '1TB PCIe SSD',
    display: '16" WQXGA 2560×1600 165Hz IPS Anti-Glare',
    battery: '80Wh – up to 6 hours',
    weight: 2.4,
    description: 'Accessible gateway into premium gaming. Legion delivers solid mid-tier gaming performance with excellent thermal management and a vibrant 165Hz display at an approachable price.',
    gamingScore: 82, codingScore: 82, productivityScore: 80, batteryScore: 62,
    cpuOptions: [ConfigOption(name: 'AMD Ryzen 7 7745HX', priceDelta: 0.0)],
    gpuOptions: [
      ConfigOption(name: 'NVIDIA RTX 4060 (8GB)', priceDelta: 0.0),
      ConfigOption(name: 'NVIDIA RTX 4070 (8GB)', priceDelta: 200.0),
    ],
    ramOptions: [
      ConfigOption(name: '16GB DDR5', priceDelta: 0.0),
      ConfigOption(name: '32GB DDR5', priceDelta: 100.0),
    ],
    storageOptions: [
      ConfigOption(name: '1TB PCIe SSD', priceDelta: 0.0),
    ],
    reviews: [
      LaptopReview(username: 'BudgetGamer', rating: 4.6, date: '2026-06-10', comment: 'Great mid-tier gaming machine. Runs everything at high settings smoothly.'),
    ],
  ),

  Laptop(
    id: 'lenovo_06',
    name: 'ThinkPad P16s Gen 2',
    brand: 'Lenovo',
    basePrice: 1899.00,
    imageUrl: 'https://images.unsplash.com/photo-1611186871348-b1ce696e52c9?w=800&auto=format&fit=crop&q=80',
    category: 'Business',
    rating: 4.71,
    reviewsCount: 44,
    cpu: 'AMD Ryzen 7 PRO 7840U',
    gpu: 'AMD Radeon 780M + NVIDIA RTX A500 (4GB)',
    ram: '32GB DDR5',
    storage: '1TB SSD',
    display: '16" WUXGA 1920×1200 60Hz IPS',
    battery: '86Wh – up to 14 hours',
    weight: 1.74,
    description: 'ISV-certified workstation in a slim package. Nvidia RTX A500 professional GPU, ECC memory support, and military-grade durability for engineers and architects.',
    gamingScore: 60, codingScore: 90, productivityScore: 96, batteryScore: 86,
    cpuOptions: [ConfigOption(name: 'AMD Ryzen 7 PRO 7840U', priceDelta: 0.0)],
    gpuOptions: [ConfigOption(name: 'NVIDIA RTX A500 (4GB)', priceDelta: 0.0)],
    ramOptions: [
      ConfigOption(name: '16GB DDR5', priceDelta: -100.0),
      ConfigOption(name: '32GB DDR5', priceDelta: 0.0),
      ConfigOption(name: '64GB DDR5', priceDelta: 200.0),
    ],
    storageOptions: [
      ConfigOption(name: '512GB SSD', priceDelta: -80.0),
      ConfigOption(name: '1TB SSD', priceDelta: 0.0),
      ConfigOption(name: '2TB SSD', priceDelta: 120.0),
    ],
    reviews: [
      LaptopReview(username: 'CADengineer', rating: 4.7, date: '2026-05-30', comment: 'ISV certification is a must for my AutoCAD work. Very reliable.'),
    ],
  ),

  // ==================== HP ====================
  Laptop(
    id: 'hp_01',
    name: 'Spectre x360 16 OLED 2-in-1',
    brand: 'HP',
    basePrice: 1999.00,
    imageUrl: 'https://images.unsplash.com/photo-1531297484001-80022131f5a1?w=800&auto=format&fit=crop&q=80',
    category: 'Ultra-portable',
    rating: 4.78,
    reviewsCount: 91,
    cpu: 'Intel Core Ultra 7 155H',
    gpu: 'Intel Arc Graphics + NVIDIA RTX 4050 (6GB)',
    ram: '32GB LPDDR5X',
    storage: '2TB PCIe Gen4 SSD',
    display: '16" 4K OLED Touch 3840×2400',
    battery: '83Wh – up to 13 hours',
    weight: 2.07,
    description: 'HP\'s masterpiece 2-in-1 with a 4K OLED touchscreen. Gem-cut design, premium speakers, active pen support, and NVIDIA discrete graphics make this the luxury 2-in-1 for pros.',
    gamingScore: 62, codingScore: 88, productivityScore: 96, batteryScore: 85,
    cpuOptions: [ConfigOption(name: 'Intel Core Ultra 7 155H', priceDelta: 0.0)],
    gpuOptions: [
      ConfigOption(name: 'Intel Arc + RTX 4050 (6GB)', priceDelta: 0.0),
    ],
    ramOptions: [
      ConfigOption(name: '16GB LPDDR5X', priceDelta: -200.0),
      ConfigOption(name: '32GB LPDDR5X', priceDelta: 0.0),
    ],
    storageOptions: [
      ConfigOption(name: '1TB PCIe SSD', priceDelta: -200.0),
      ConfigOption(name: '2TB PCIe SSD', priceDelta: 0.0),
    ],
    reviews: [
      LaptopReview(username: 'TabletLover', rating: 5.0, date: '2026-07-05', comment: '4K OLED in tablet mode is unbelievable for reading and sketching.'),
      LaptopReview(username: 'PremiumPickr', rating: 4.5, date: '2026-06-28', comment: 'Design is absolutely premium. Feels like jewelry.'),
    ],
  ),

  Laptop(
    id: 'hp_02',
    name: 'Spectre x360 14 Gem-Cut',
    brand: 'HP',
    basePrice: 1499.00,
    imageUrl: 'https://images.unsplash.com/photo-1541807084-5c52b6b3adef?w=800&auto=format&fit=crop&q=80',
    category: 'Ultra-portable',
    rating: 4.65,
    reviewsCount: 94,
    cpu: 'Intel Core Ultra 7 155U',
    gpu: 'Intel Graphics',
    ram: '16GB LPDDR5X',
    storage: '1TB PCIe Gen4 NVMe',
    display: '14" 2.8K OLED Touch (3:2 aspect)',
    battery: '68Wh – up to 13 hours',
    weight: 1.44,
    description: 'Stunning gem-cut design meets 2-in-1 versatility. Rotate the 3:2 OLED display to tablet or tent mode, draw with the rechargeable tilt pen, and enjoy premium Poly Studio audio.',
    gamingScore: 50, codingScore: 82, productivityScore: 92, batteryScore: 89,
    cpuOptions: [
      ConfigOption(name: 'Intel Core Ultra 5 125U', priceDelta: -120.0),
      ConfigOption(name: 'Intel Core Ultra 7 155U', priceDelta: 0.0),
    ],
    gpuOptions: [ConfigOption(name: 'Intel Graphics', priceDelta: 0.0)],
    ramOptions: [
      ConfigOption(name: '16GB LPDDR5X', priceDelta: 0.0),
      ConfigOption(name: '32GB LPDDR5X', priceDelta: 100.0),
    ],
    storageOptions: [
      ConfigOption(name: '1TB PCIe SSD', priceDelta: 0.0),
      ConfigOption(name: '2TB PCIe SSD', priceDelta: 90.0),
    ],
    reviews: [
      LaptopReview(username: 'Clara Oswald', rating: 5.0, date: '2026-06-20', comment: 'Blue color with brass accents looks luxurious. Tablet mode is very useful.'),
    ],
  ),

  Laptop(
    id: 'hp_03',
    name: 'Omen Transcend 16 OLED',
    brand: 'HP',
    basePrice: 1899.00,
    imageUrl: 'https://images.unsplash.com/photo-1504707748692-419802cf939d?w=800&auto=format&fit=crop&q=80',
    category: 'Gaming',
    rating: 4.71,
    reviewsCount: 52,
    cpu: 'Intel Core i7-14700HX',
    gpu: 'NVIDIA RTX 4070 (8GB)',
    ram: '16GB DDR5',
    storage: '1TB PCIe NVMe SSD',
    display: '16" 2.5K 2560×1600 240Hz OLED',
    battery: '97Wh – up to 7 hours',
    weight: 2.1,
    description: 'Premium thin-and-light gaming with a gorgeous 240Hz OLED display. Powerful thermal dynamics deliver high frame rates without bulk.',
    gamingScore: 92, codingScore: 88, productivityScore: 84, batteryScore: 68,
    cpuOptions: [
      ConfigOption(name: 'Intel Core i7-14700HX', priceDelta: 0.0),
      ConfigOption(name: 'Intel Core i9-14900HX', priceDelta: 200.0),
    ],
    gpuOptions: [ConfigOption(name: 'NVIDIA RTX 4070 (8GB)', priceDelta: 0.0)],
    ramOptions: [
      ConfigOption(name: '16GB DDR5', priceDelta: 0.0),
      ConfigOption(name: '32GB DDR5', priceDelta: 120.0),
    ],
    storageOptions: [
      ConfigOption(name: '1TB PCIe SSD', priceDelta: 0.0),
      ConfigOption(name: '2TB PCIe SSD', priceDelta: 100.0),
    ],
    reviews: [
      LaptopReview(username: 'Marc9', rating: 4.5, date: '2026-07-03', comment: 'Beautiful screen. Light enough for work, powerful enough for night gaming.'),
    ],
  ),

  Laptop(
    id: 'hp_04',
    name: 'EliteBook 1040 G11',
    brand: 'HP',
    basePrice: 1599.00,
    imageUrl: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=800&auto=format&fit=crop&q=80',
    category: 'Business',
    rating: 4.62,
    reviewsCount: 23,
    cpu: 'Intel Core Ultra 7 165U',
    gpu: 'Intel Arc Graphics',
    ram: '16GB LPDDR5X',
    storage: '512GB PCIe SSD',
    display: '14" WUXGA 1920×1200 Anti-Glare HP Sure View Privacy',
    battery: '56Wh – up to 14 hours',
    weight: 1.18,
    description: 'Enterprise leadership with HP Sure View privacy display. Advanced collaboration features, built-in AI noise cancellation, and enterprise-grade security make this ideal for executives.',
    gamingScore: 40, codingScore: 86, productivityScore: 95, batteryScore: 90,
    cpuOptions: [ConfigOption(name: 'Intel Core Ultra 7 165U', priceDelta: 0.0)],
    gpuOptions: [ConfigOption(name: 'Intel Arc Graphics', priceDelta: 0.0)],
    ramOptions: [
      ConfigOption(name: '16GB LPDDR5X', priceDelta: 0.0),
      ConfigOption(name: '32GB LPDDR5X', priceDelta: 120.0),
    ],
    storageOptions: [
      ConfigOption(name: '512GB PCIe SSD', priceDelta: 0.0),
      ConfigOption(name: '1TB PCIe SSD', priceDelta: 80.0),
    ],
    reviews: [
      LaptopReview(username: 'ExecIT', rating: 4.8, date: '2026-06-05', comment: 'Privacy screen is essential for flights. Solid performance for executives.'),
    ],
  ),

  Laptop(
    id: 'hp_05',
    name: 'Omen 17 RTX 4090 Desktop',
    brand: 'HP',
    basePrice: 2899.00,
    imageUrl: 'https://images.unsplash.com/photo-1629429408209-1f912961dbd8?w=800&auto=format&fit=crop&q=80',
    category: 'Gaming',
    rating: 4.80,
    reviewsCount: 38,
    cpu: 'Intel Core i9-14900HX',
    gpu: 'NVIDIA RTX 4090 (16GB)',
    ram: '32GB DDR5',
    storage: '2TB NVMe SSD',
    display: '17.3" QHD 2560×1440 165Hz IPS',
    battery: '99Wh – up to 4 hours',
    weight: 3.2,
    description: 'HP\'s mightiest gaming beast. Full-power RTX 4090, Intel Core i9 at max TDP, advanced liquid-metal thermal solution, and vibrant 165Hz QHD display. Desktop gaming power unchained.',
    gamingScore: 100, codingScore: 94, productivityScore: 80, batteryScore: 38,
    cpuOptions: [ConfigOption(name: 'Intel Core i9-14900HX', priceDelta: 0.0)],
    gpuOptions: [
      ConfigOption(name: 'NVIDIA RTX 4080 (12GB)', priceDelta: -500.0),
      ConfigOption(name: 'NVIDIA RTX 4090 (16GB)', priceDelta: 0.0),
    ],
    ramOptions: [
      ConfigOption(name: '32GB DDR5', priceDelta: 0.0),
      ConfigOption(name: '64GB DDR5', priceDelta: 200.0),
    ],
    storageOptions: [
      ConfigOption(name: '1TB NVMe SSD', priceDelta: -150.0),
      ConfigOption(name: '2TB NVMe SSD', priceDelta: 0.0),
    ],
    reviews: [
      LaptopReview(username: 'PowerUser', rating: 5.0, date: '2026-07-09', comment: 'Finally an HP that competes with Alienware. Absolute powerhouse.'),
    ],
  ),

  Laptop(
    id: 'hp_06',
    name: 'ZBook Fury 16 G11',
    brand: 'HP',
    basePrice: 3299.00,
    imageUrl: 'https://images.unsplash.com/photo-1496181130204-755241544e35?w=800&auto=format&fit=crop&q=80',
    category: 'Creators',
    rating: 4.76,
    reviewsCount: 19,
    cpu: 'Intel Core i9-14900HX',
    gpu: 'NVIDIA RTX 5000 Ada (16GB)',
    ram: '64GB DDR5 ECC',
    storage: '2TB NVMe SSD',
    display: '16" DreamColor 4K UHD 3840×2400 OLED Touch',
    battery: '96Wh – up to 8 hours',
    weight: 2.54,
    description: 'ISV-certified professional mobile workstation. RTX 5000 Ada professional GPU with 16GB VRAM, ECC memory, and HP DreamColor 4K OLED display for the most demanding creative and scientific workflows.',
    gamingScore: 90, codingScore: 98, productivityScore: 99, batteryScore: 70,
    cpuOptions: [ConfigOption(name: 'Intel Core i9-14900HX', priceDelta: 0.0)],
    gpuOptions: [
      ConfigOption(name: 'NVIDIA RTX A2000 (8GB)', priceDelta: -900.0),
      ConfigOption(name: 'NVIDIA RTX 5000 Ada (16GB)', priceDelta: 0.0),
    ],
    ramOptions: [
      ConfigOption(name: '32GB DDR5 ECC', priceDelta: -300.0),
      ConfigOption(name: '64GB DDR5 ECC', priceDelta: 0.0),
      ConfigOption(name: '128GB DDR5 ECC', priceDelta: 600.0),
    ],
    storageOptions: [
      ConfigOption(name: '2TB NVMe SSD', priceDelta: 0.0),
      ConfigOption(name: '4TB NVMe SSD', priceDelta: 300.0),
    ],
    reviews: [
      LaptopReview(username: 'CFDengineer', rating: 5.0, date: '2026-06-25', comment: 'RTX 5000 Ada handles our simulation workloads flawlessly. DreamColor display is perfect for visualization.'),
    ],
  ),

  // ==================== DELL ====================
  Laptop(
    id: 'dell_01',
    name: 'Alienware x18 R2',
    brand: 'Dell',
    basePrice: 3799.00,
    imageUrl: 'https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=800&auto=format&fit=crop&q=80',
    category: 'Gaming',
    rating: 4.91,
    reviewsCount: 42,
    cpu: 'Intel Core i9-14900HX',
    gpu: 'NVIDIA RTX 4090 (16GB)',
    ram: '64GB DDR5',
    storage: '4TB NVMe SSD',
    display: '18" QHD+ 2560×1600 480Hz IPS',
    battery: '97Wh – up to 4 hours',
    weight: 4.3,
    description: 'The biggest, most extreme gaming laptop ever made. 18-inch chassis with 480Hz display, full RTX 4090, and Alienware\'s legendary thermal design. True desktop replacement royalty.',
    gamingScore: 100, codingScore: 96, productivityScore: 84, batteryScore: 35,
    cpuOptions: [ConfigOption(name: 'Intel Core i9-14900HX', priceDelta: 0.0)],
    gpuOptions: [
      ConfigOption(name: 'NVIDIA RTX 4080 (12GB)', priceDelta: -600.0),
      ConfigOption(name: 'NVIDIA RTX 4090 (16GB)', priceDelta: 0.0),
    ],
    ramOptions: [
      ConfigOption(name: '32GB DDR5', priceDelta: -300.0),
      ConfigOption(name: '64GB DDR5', priceDelta: 0.0),
      ConfigOption(name: '128GB DDR5', priceDelta: 500.0),
    ],
    storageOptions: [
      ConfigOption(name: '2TB NVMe SSD', priceDelta: -200.0),
      ConfigOption(name: '4TB NVMe SSD', priceDelta: 0.0),
    ],
    reviews: [
      LaptopReview(username: 'AlienFan', rating: 5.0, date: '2026-07-11', comment: '480Hz is something you have to see to believe. Every game is a slideshow of perfection.'),
      LaptopReview(username: 'MaxPerf', rating: 4.8, date: '2026-07-06', comment: 'Pure power. Handles everything at max settings without flinching.'),
    ],
  ),

  Laptop(
    id: 'dell_02',
    name: 'Alienware x16 R2',
    brand: 'Dell',
    basePrice: 2899.00,
    imageUrl: 'https://images.unsplash.com/photo-1593642632823-8f785ba67e45?w=800&auto=format&fit=crop&q=80',
    category: 'Gaming',
    rating: 4.85,
    reviewsCount: 71,
    cpu: 'Intel Core Ultra 9 185H',
    gpu: 'NVIDIA RTX 4090 (16GB)',
    ram: '32GB LPDDR5X',
    storage: '2TB RAID 0 SSD',
    display: '16" QHD+ 2560×1600 240Hz G-SYNC',
    battery: '90Wh – up to 5 hours',
    weight: 2.72,
    description: 'Lunar Silver gaming juggernaut. Cryo-Tech vapor chamber cooling, 31-zone AlienFX lighting, and full RTX 4090 in Alienware\'s ultra-slim chassis.',
    gamingScore: 100, codingScore: 92, productivityScore: 82, batteryScore: 45,
    cpuOptions: [
      ConfigOption(name: 'Intel Core Ultra 7 155H', priceDelta: -200.0),
      ConfigOption(name: 'Intel Core Ultra 9 185H', priceDelta: 0.0),
    ],
    gpuOptions: [
      ConfigOption(name: 'NVIDIA RTX 4080 (12GB)', priceDelta: -450.0),
      ConfigOption(name: 'NVIDIA RTX 4090 (16GB)', priceDelta: 0.0),
    ],
    ramOptions: [
      ConfigOption(name: '16GB LPDDR5X', priceDelta: -100.0),
      ConfigOption(name: '32GB LPDDR5X', priceDelta: 0.0),
    ],
    storageOptions: [
      ConfigOption(name: '1TB NVMe SSD', priceDelta: -150.0),
      ConfigOption(name: '2TB NVMe SSD (RAID 0)', priceDelta: 0.0),
      ConfigOption(name: '4TB NVMe SSD (RAID 0)', priceDelta: 300.0),
    ],
    reviews: [
      LaptopReview(username: 'FragMaster', rating: 5.0, date: '2026-05-15', comment: 'Vapor chamber cooling keeps it running smooth at max FPS. Flawless build quality.'),
    ],
  ),

  Laptop(
    id: 'dell_03',
    name: 'XPS 16 OLED 2-in-1',
    brand: 'Dell',
    basePrice: 2599.00,
    imageUrl: 'https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?w=800&auto=format&fit=crop&q=80',
    category: 'Creators',
    rating: 4.84,
    reviewsCount: 58,
    cpu: 'Intel Core Ultra 9 185H',
    gpu: 'NVIDIA RTX 4060 (8GB)',
    ram: '32GB DDR5',
    storage: '1TB PCIe SSD',
    display: '16.3" 4K+ OLED Touch 3200×2000',
    battery: '99.5Wh – up to 10 hours',
    weight: 1.83,
    description: 'Dell\'s greatest XPS ever. Stunning 4K+ OLED touchscreen with InfinityEdge bezels, 2-in-1 capability, and Core Ultra 9 performance in the industry\'s most premium ultrabook design.',
    gamingScore: 74, codingScore: 96, productivityScore: 98, batteryScore: 76,
    cpuOptions: [ConfigOption(name: 'Intel Core Ultra 9 185H', priceDelta: 0.0)],
    gpuOptions: [
      ConfigOption(name: 'NVIDIA RTX 4060 (8GB)', priceDelta: 0.0),
    ],
    ramOptions: [
      ConfigOption(name: '16GB DDR5', priceDelta: -150.0),
      ConfigOption(name: '32GB DDR5', priceDelta: 0.0),
      ConfigOption(name: '64GB DDR5', priceDelta: 300.0),
    ],
    storageOptions: [
      ConfigOption(name: '1TB PCIe SSD', priceDelta: 0.0),
      ConfigOption(name: '2TB PCIe SSD', priceDelta: 200.0),
    ],
    reviews: [
      LaptopReview(username: 'XPSfan', rating: 5.0, date: '2026-07-08', comment: '4K+ OLED with barely any bezel is absolutely gorgeous. The 2-in-1 hinge feels premium.'),
    ],
  ),

  Laptop(
    id: 'dell_04',
    name: 'XPS 15 OLED',
    brand: 'Dell',
    basePrice: 2099.00,
    imageUrl: 'https://images.unsplash.com/photo-1541807084-5c52b6b3adef?w=800&auto=format&fit=crop&q=80',
    category: 'Creators',
    rating: 4.78,
    reviewsCount: 142,
    cpu: 'Intel Core i9-13900H',
    gpu: 'NVIDIA RTX 4060 (8GB)',
    ram: '32GB DDR5',
    storage: '1TB PCIe SSD',
    display: '15.6" 3.5K 3456×2160 InfinityEdge OLED Touch',
    battery: '86Wh – up to 9 hours',
    weight: 1.92,
    description: 'Borderless visual experience. The 3.5K InfinityEdge OLED touchscreen brings true-to-life color in a premium machined aluminum and carbon fiber chassis.',
    gamingScore: 72, codingScore: 96, productivityScore: 94, batteryScore: 75,
    cpuOptions: [
      ConfigOption(name: 'Intel Core i7-13700H', priceDelta: -150.0),
      ConfigOption(name: 'Intel Core i9-13900H', priceDelta: 0.0),
    ],
    gpuOptions: [
      ConfigOption(name: 'NVIDIA RTX 4060 (8GB)', priceDelta: 0.0),
      ConfigOption(name: 'NVIDIA RTX 4070 (8GB)', priceDelta: 200.0),
    ],
    ramOptions: [
      ConfigOption(name: '16GB DDR5', priceDelta: -100.0),
      ConfigOption(name: '32GB DDR5', priceDelta: 0.0),
      ConfigOption(name: '64GB DDR5', priceDelta: 250.0),
    ],
    storageOptions: [
      ConfigOption(name: '1TB PCIe SSD', priceDelta: 0.0),
      ConfigOption(name: '2TB PCIe SSD', priceDelta: 120.0),
    ],
    reviews: [
      LaptopReview(username: 'VinceL', rating: 5.0, date: '2026-06-18', comment: 'Almost zero bezel. Screen looks like it is floating. Incredible keyboard feel.'),
    ],
  ),

  Laptop(
    id: 'dell_05',
    name: 'Precision 5690 Workstation',
    brand: 'Dell',
    basePrice: 3199.00,
    imageUrl: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=800&auto=format&fit=crop&q=80',
    category: 'Creators',
    rating: 4.79,
    reviewsCount: 27,
    cpu: 'Intel Core Ultra 9 185H',
    gpu: 'NVIDIA RTX A2000 (8GB)',
    ram: '64GB DDR5',
    storage: '2TB NVMe SSD',
    display: '16" 4K+ OLED Touch 3840×2400',
    battery: '99.5Wh – up to 9 hours',
    weight: 1.88,
    description: 'ISV-certified mobile workstation meets premium ultrabook design. The Precision 5690 delivers reliable RTX professional graphics, ECC memory, and a jaw-dropping 4K+ OLED display for the world\'s most demanding workflows.',
    gamingScore: 80, codingScore: 99, productivityScore: 99, batteryScore: 77,
    cpuOptions: [ConfigOption(name: 'Intel Core Ultra 9 185H', priceDelta: 0.0)],
    gpuOptions: [
      ConfigOption(name: 'NVIDIA RTX A1000 (6GB)', priceDelta: -400.0),
      ConfigOption(name: 'NVIDIA RTX A2000 (8GB)', priceDelta: 0.0),
    ],
    ramOptions: [
      ConfigOption(name: '32GB DDR5', priceDelta: -300.0),
      ConfigOption(name: '64GB DDR5', priceDelta: 0.0),
      ConfigOption(name: '128GB DDR5', priceDelta: 600.0),
    ],
    storageOptions: [
      ConfigOption(name: '1TB NVMe SSD', priceDelta: -150.0),
      ConfigOption(name: '2TB NVMe SSD', priceDelta: 0.0),
      ConfigOption(name: '4TB NVMe SSD', priceDelta: 400.0),
    ],
    reviews: [
      LaptopReview(username: 'SimAnalyst', rating: 5.0, date: '2026-06-30', comment: '4K OLED with professional GPU at 1.88 kg is a miracle. Best workstation laptop bar none.'),
    ],
  ),

  Laptop(
    id: 'dell_06',
    name: 'Inspiron 16 Plus 7640',
    brand: 'Dell',
    basePrice: 1099.00,
    imageUrl: 'https://images.unsplash.com/photo-1496181130204-755241544e35?w=800&auto=format&fit=crop&q=80',
    category: 'Creators',
    rating: 4.54,
    reviewsCount: 37,
    cpu: 'Intel Core Ultra 7 155H',
    gpu: 'Intel Arc Graphics',
    ram: '16GB DDR5',
    storage: '1TB PCIe NVMe SSD',
    display: '16" 2.5K 2560×1600 120Hz Anti-Glare',
    battery: '90Wh – up to 11 hours',
    weight: 2.06,
    description: 'Versatile mid-tier creator machine. Generous 16" 120Hz display, long battery life, Intel Core Ultra performance for coding and content creation at an accessible price.',
    gamingScore: 50, codingScore: 85, productivityScore: 90, batteryScore: 88,
    cpuOptions: [ConfigOption(name: 'Intel Core Ultra 7 155H', priceDelta: 0.0)],
    gpuOptions: [ConfigOption(name: 'Intel Arc Graphics', priceDelta: 0.0)],
    ramOptions: [
      ConfigOption(name: '16GB DDR5', priceDelta: 0.0),
      ConfigOption(name: '32GB DDR5', priceDelta: 120.0),
    ],
    storageOptions: [
      ConfigOption(name: '1TB PCIe SSD', priceDelta: 0.0),
      ConfigOption(name: '2TB PCIe SSD', priceDelta: 100.0),
    ],
    reviews: [
      LaptopReview(username: 'EvaCode', rating: 4.5, date: '2026-07-01', comment: '16" workspace makes coding on-the-go very comfortable. Great value.'),
    ],
  ),

  // ==================== APPLE – extra ====================
  Laptop(
    id: 'apple_07',
    name: 'MacBook Pro 16 M2 Ultra',
    brand: 'Apple',
    basePrice: 3999.00,
    imageUrl: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=800&auto=format&fit=crop&q=80',
    category: 'Creators',
    rating: 4.93,
    reviewsCount: 198,
    cpu: 'Apple M2 Ultra (24-Core)',
    gpu: '76-Core GPU',
    ram: '192GB Unified Memory',
    storage: '1TB SSD',
    display: '16.2" Liquid Retina XDR 3456x2234 120Hz',
    battery: '100Wh – up to 22 hours',
    weight: 2.15,
    description: 'Workstation power in a laptop. M2 Ultra with 76-core GPU and up to 192 GB unified memory handles the most extreme creative and ML pipelines without compromise.',
    gamingScore: 80, codingScore: 100, productivityScore: 100, batteryScore: 98,
    cpuOptions: [
      ConfigOption(name: 'M2 Max 12-Core / 38-Core GPU', priceDelta: -1200.0),
      ConfigOption(name: 'M2 Ultra 24-Core / 76-Core GPU', priceDelta: 0.0),
    ],
    gpuOptions: [ConfigOption(name: 'Integrated Apple GPU', priceDelta: 0.0)],
    ramOptions: [
      ConfigOption(name: '96GB Unified Memory', priceDelta: -600.0),
      ConfigOption(name: '192GB Unified Memory', priceDelta: 0.0),
    ],
    storageOptions: [
      ConfigOption(name: '1TB SSD', priceDelta: 0.0),
      ConfigOption(name: '2TB SSD', priceDelta: 400.0),
      ConfigOption(name: '4TB SSD', priceDelta: 1000.0),
      ConfigOption(name: '8TB SSD', priceDelta: 2200.0),
    ],
    reviews: [
      LaptopReview(username: 'AIResearcher', rating: 5.0, date: '2026-06-02', comment: 'Running 70B LLMs locally is real with 192 GB unified. Unbelievable.'),
    ],
  ),
  Laptop(
    id: 'apple_08',
    name: 'MacBook Air 13 M2',
    brand: 'Apple',
    basePrice: 999.00,
    imageUrl: 'https://images.unsplash.com/photo-1589642380614-4a8c2aaa09c7?w=800&auto=format&fit=crop&q=80',
    category: 'Ultra-portable',
    rating: 4.72,
    reviewsCount: 340,
    cpu: 'Apple M2 (8-Core)',
    gpu: '10-Core GPU',
    ram: '8GB Unified Memory',
    storage: '256GB SSD',
    display: '13.6" Liquid Retina 2560x1664',
    battery: '52.6Wh – up to 18 hours',
    weight: 1.24,
    description: 'The redesigned M2 Air in Midnight and Starlight. MagSafe charging, all-day battery, and silent fanless design in the world\'s most popular laptop form factor.',
    gamingScore: 38, codingScore: 78, productivityScore: 88, batteryScore: 94,
    cpuOptions: [ConfigOption(name: 'Apple M2 8-Core', priceDelta: 0.0)],
    gpuOptions: [
      ConfigOption(name: '8-Core GPU', priceDelta: -50.0),
      ConfigOption(name: '10-Core GPU', priceDelta: 0.0),
    ],
    ramOptions: [
      ConfigOption(name: '8GB Unified Memory', priceDelta: 0.0),
      ConfigOption(name: '16GB Unified Memory', priceDelta: 200.0),
      ConfigOption(name: '24GB Unified Memory', priceDelta: 400.0),
    ],
    storageOptions: [
      ConfigOption(name: '256GB SSD', priceDelta: 0.0),
      ConfigOption(name: '512GB SSD', priceDelta: 200.0),
      ConfigOption(name: '1TB SSD', priceDelta: 400.0),
      ConfigOption(name: '2TB SSD', priceDelta: 800.0),
    ],
    reviews: [
      LaptopReview(username: 'CollegeStudent', rating: 4.7, date: '2026-05-14', comment: 'Perfect for university – silent, lasts all day, fits in any bag.'),
    ],
  ),
  Laptop(
    id: 'apple_09',
    name: 'MacBook Pro 14 M2 Max',
    brand: 'Apple',
    basePrice: 2399.00,
    imageUrl: 'https://images.unsplash.com/photo-1531297484001-80022131f5a1?w=800&auto=format&fit=crop&q=80',
    category: 'Business',
    rating: 4.86,
    reviewsCount: 120,
    cpu: 'Apple M2 Max (12-Core)',
    gpu: '30-Core GPU',
    ram: '32GB Unified Memory',
    storage: '512GB SSD',
    display: '14.2" Liquid Retina XDR 3024x1964 120Hz',
    battery: '70Wh – up to 18 hours',
    weight: 1.63,
    description: 'Compact workstation with M2 Max. Ideal for engineers and video editors who demand workstation-level performance in a 14-inch chassis with exceptional battery life.',
    gamingScore: 62, codingScore: 96, productivityScore: 98, batteryScore: 91,
    cpuOptions: [
      ConfigOption(name: 'M2 Max 10-Core / 24-Core GPU', priceDelta: -300.0),
      ConfigOption(name: 'M2 Max 12-Core / 30-Core GPU', priceDelta: 0.0),
    ],
    gpuOptions: [ConfigOption(name: 'Integrated Apple GPU', priceDelta: 0.0)],
    ramOptions: [
      ConfigOption(name: '32GB Unified Memory', priceDelta: 0.0),
      ConfigOption(name: '64GB Unified Memory', priceDelta: 400.0),
      ConfigOption(name: '96GB Unified Memory', priceDelta: 800.0),
    ],
    storageOptions: [
      ConfigOption(name: '512GB SSD', priceDelta: 0.0),
      ConfigOption(name: '1TB SSD', priceDelta: 200.0),
      ConfigOption(name: '2TB SSD', priceDelta: 600.0),
    ],
    reviews: [
      LaptopReview(username: 'MobileArchitect', rating: 5.0, date: '2026-04-22', comment: 'Compiles entire Swift packages in seconds. Screen quality unmatched.'),
    ],
  ),

  // ==================== RAZER – extra ====================
  Laptop(
    id: 'razer_06',
    name: 'Blade Stealth 13 Ultra',
    brand: 'Razer',
    basePrice: 1599.00,
    imageUrl: 'https://images.unsplash.com/photo-1603302576837-37561b2e2302?w=800&auto=format&fit=crop&q=80',
    category: 'Ultra-portable',
    rating: 4.72,
    reviewsCount: 56,
    cpu: 'Intel Core i7-1260P',
    gpu: 'Intel Iris Xe + NVIDIA RTX 3050 Ti (4GB)',
    ram: '16GB LPDDR5',
    storage: '512GB NVMe SSD',
    display: '13.4" FHD+ 1920x1200 144Hz IPS',
    battery: '55.2Wh – up to 10 hours',
    weight: 1.49,
    description: 'The sleekest gaming ultrabook. Gunmetal CNC aluminum, per-key Chroma RGB, and discrete RTX graphics in a 13.4-inch package that fits anywhere.',
    gamingScore: 65, codingScore: 85, productivityScore: 88, batteryScore: 78,
    cpuOptions: [ConfigOption(name: 'Intel Core i7-1260P', priceDelta: 0.0)],
    gpuOptions: [
      ConfigOption(name: 'Intel Iris Xe only', priceDelta: -200.0),
      ConfigOption(name: 'Intel Iris Xe + NVIDIA RTX 3050 Ti', priceDelta: 0.0),
    ],
    ramOptions: [
      ConfigOption(name: '16GB LPDDR5', priceDelta: 0.0),
      ConfigOption(name: '32GB LPDDR5', priceDelta: 100.0),
    ],
    storageOptions: [
      ConfigOption(name: '512GB NVMe SSD', priceDelta: 0.0),
      ConfigOption(name: '1TB NVMe SSD', priceDelta: 80.0),
    ],
    reviews: [
      LaptopReview(username: 'TravelGamer', rating: 4.7, date: '2026-05-30', comment: 'So thin I forgot it was in my bag. Handles Fortnite and League perfectly.'),
    ],
  ),
  Laptop(
    id: 'razer_07',
    name: 'Blade 16 OLED 2024',
    brand: 'Razer',
    basePrice: 2699.00,
    imageUrl: 'https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=800&auto=format&fit=crop&q=80',
    category: 'Gaming',
    rating: 4.87,
    reviewsCount: 79,
    cpu: 'Intel Core i9-14900HX',
    gpu: 'NVIDIA RTX 4080 (12GB)',
    ram: '32GB DDR5',
    storage: '1TB PCIe Gen4 SSD',
    display: '16" 2.5K 2560x1600 240Hz OLED',
    battery: '95Wh – up to 6 hours',
    weight: 2.36,
    description: 'Razor-thin 16-inch gaming machine with RTX 4080 and a breathtaking 240Hz OLED panel. Vapor chamber cooling keeps thermals in check under sustained loads.',
    gamingScore: 97, codingScore: 93, productivityScore: 88, batteryScore: 58,
    cpuOptions: [ConfigOption(name: 'Intel Core i9-14900HX', priceDelta: 0.0)],
    gpuOptions: [
      ConfigOption(name: 'NVIDIA RTX 4070 (8GB)', priceDelta: -400.0),
      ConfigOption(name: 'NVIDIA RTX 4080 (12GB)', priceDelta: 0.0),
    ],
    ramOptions: [
      ConfigOption(name: '16GB DDR5', priceDelta: -100.0),
      ConfigOption(name: '32GB DDR5', priceDelta: 0.0),
      ConfigOption(name: '64GB DDR5', priceDelta: 250.0),
    ],
    storageOptions: [
      ConfigOption(name: '1TB PCIe SSD', priceDelta: 0.0),
      ConfigOption(name: '2TB PCIe SSD', priceDelta: 150.0),
    ],
    reviews: [
      LaptopReview(username: 'BladeHead', rating: 5.0, date: '2026-06-18', comment: 'The OLED is gorgeous for gaming at night. Colors pop like nothing else.'),
    ],
  ),
  Laptop(
    id: 'razer_08',
    name: 'Blade 14 Titanium',
    brand: 'Razer',
    basePrice: 2299.00,
    imageUrl: 'https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?w=800&auto=format&fit=crop&q=80',
    category: 'Gaming',
    rating: 4.83,
    reviewsCount: 44,
    cpu: 'AMD Ryzen 9 8945HX',
    gpu: 'NVIDIA RTX 4080 (12GB)',
    ram: '32GB DDR5',
    storage: '1TB PCIe Gen4 SSD',
    display: '14" 2.8K 2880x1800 165Hz OLED',
    battery: '82Wh – up to 8 hours',
    weight: 1.72,
    description: 'Maximum power in the smallest Razer chassis. Ryzen 9 + RTX 4080 with anodized titanium finish – the most powerful 14-inch gaming laptop available.',
    gamingScore: 98, codingScore: 92, productivityScore: 86, batteryScore: 72,
    cpuOptions: [ConfigOption(name: 'AMD Ryzen 9 8945HX', priceDelta: 0.0)],
    gpuOptions: [
      ConfigOption(name: 'NVIDIA RTX 4070 (8GB)', priceDelta: -300.0),
      ConfigOption(name: 'NVIDIA RTX 4080 (12GB)', priceDelta: 0.0),
    ],
    ramOptions: [
      ConfigOption(name: '16GB DDR5', priceDelta: -150.0),
      ConfigOption(name: '32GB DDR5', priceDelta: 0.0),
      ConfigOption(name: '64GB DDR5', priceDelta: 250.0),
    ],
    storageOptions: [
      ConfigOption(name: '1TB PCIe SSD', priceDelta: 0.0),
      ConfigOption(name: '2TB PCIe SSD', priceDelta: 150.0),
    ],
    reviews: [
      LaptopReview(username: 'CompactBeast', rating: 4.8, date: '2026-07-05', comment: 'RTX 4080 in 14" is pure magic. Titanium finish feels incredible.'),
    ],
  ),

  // ==================== ASUS – extra ====================
  Laptop(
    id: 'asus_07',
    name: 'ROG Flow X16 2-in-1',
    brand: 'ASUS',
    basePrice: 2199.00,
    imageUrl: 'https://images.unsplash.com/photo-1593642632823-8f785ba67e45?w=800&auto=format&fit=crop&q=80',
    category: 'Gaming',
    rating: 4.70,
    reviewsCount: 63,
    cpu: 'AMD Ryzen 9 7940HX',
    gpu: 'NVIDIA RTX 4070 (8GB)',
    ram: '16GB DDR5',
    storage: '1TB PCIe Gen4 SSD',
    display: '16" QHD+ 2560x1600 165Hz IPS Touch',
    battery: '90Wh – up to 9 hours',
    weight: 2.1,
    description: 'Gaming 2-in-1 that works as a tablet, tent, or laptop. Full RTX 4070 performance with touchscreen versatility and ROG Armoury Crate tuning for all modes.',
    gamingScore: 88, codingScore: 87, productivityScore: 90, batteryScore: 76,
    cpuOptions: [ConfigOption(name: 'AMD Ryzen 9 7940HX', priceDelta: 0.0)],
    gpuOptions: [
      ConfigOption(name: 'NVIDIA RTX 4060 (8GB)', priceDelta: -200.0),
      ConfigOption(name: 'NVIDIA RTX 4070 (8GB)', priceDelta: 0.0),
    ],
    ramOptions: [
      ConfigOption(name: '16GB DDR5', priceDelta: 0.0),
      ConfigOption(name: '32GB DDR5', priceDelta: 120.0),
    ],
    storageOptions: [
      ConfigOption(name: '1TB PCIe SSD', priceDelta: 0.0),
      ConfigOption(name: '2TB PCIe SSD', priceDelta: 100.0),
    ],
    reviews: [
      LaptopReview(username: 'FlexGamer', rating: 4.7, date: '2026-06-12', comment: 'Tablet for casual games, laptop mode for serious sessions. Love it.'),
    ],
  ),
  Laptop(
    id: 'asus_08',
    name: 'TUF Gaming A17',
    brand: 'ASUS',
    basePrice: 1099.00,
    imageUrl: 'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?w=800&auto=format&fit=crop&q=80',
    category: 'Gaming',
    rating: 4.58,
    reviewsCount: 87,
    cpu: 'AMD Ryzen 7 7745HX',
    gpu: 'NVIDIA RTX 4060 (8GB)',
    ram: '16GB DDR5',
    storage: '512GB PCIe SSD',
    display: '17.3" FHD 1920x1080 144Hz IPS',
    battery: '90Wh – up to 8 hours',
    weight: 2.6,
    description: 'Military-grade durability meets budget gaming performance. TUF survives drops, spills, and extreme temps – the most reliable entry-level gaming laptop available.',
    gamingScore: 78, codingScore: 80, productivityScore: 79, batteryScore: 72,
    cpuOptions: [ConfigOption(name: 'AMD Ryzen 7 7745HX', priceDelta: 0.0)],
    gpuOptions: [
      ConfigOption(name: 'NVIDIA RTX 4050 (6GB)', priceDelta: -150.0),
      ConfigOption(name: 'NVIDIA RTX 4060 (8GB)', priceDelta: 0.0),
    ],
    ramOptions: [
      ConfigOption(name: '16GB DDR5', priceDelta: 0.0),
      ConfigOption(name: '32GB DDR5', priceDelta: 100.0),
    ],
    storageOptions: [
      ConfigOption(name: '512GB PCIe SSD', priceDelta: 0.0),
      ConfigOption(name: '1TB PCIe SSD', priceDelta: 70.0),
    ],
    reviews: [
      LaptopReview(username: 'BudgetBuilds', rating: 4.6, date: '2026-05-20', comment: 'Dropped it twice, no damage. Solid 60fps in all my games. Unbeatable value.'),
    ],
  ),
  Laptop(
    id: 'asus_09',
    name: 'ExpertBook B9 OLED',
    brand: 'ASUS',
    basePrice: 1699.00,
    imageUrl: 'https://images.unsplash.com/photo-1585076641399-5c06d1b3365f?w=800&auto=format&fit=crop&q=80',
    category: 'Business',
    rating: 4.64,
    reviewsCount: 31,
    cpu: 'Intel Core Ultra 7 155U',
    gpu: 'Intel Graphics',
    ram: '32GB LPDDR5X',
    storage: '1TB SSD',
    display: '14" 2.8K 2880x1800 120Hz OLED',
    battery: '63Wh – up to 15 hours',
    weight: 0.99,
    description: 'The world\'s lightest business laptop under 1 kg. OLED display, MIL-SPEC durability, fingerprint reader, IR camera, and TPM 2.0 – everything enterprise needs.',
    gamingScore: 35, codingScore: 85, productivityScore: 96, batteryScore: 92,
    cpuOptions: [
      ConfigOption(name: 'Intel Core Ultra 5 125U', priceDelta: -150.0),
      ConfigOption(name: 'Intel Core Ultra 7 155U', priceDelta: 0.0),
    ],
    gpuOptions: [ConfigOption(name: 'Intel Graphics', priceDelta: 0.0)],
    ramOptions: [
      ConfigOption(name: '16GB LPDDR5X', priceDelta: -100.0),
      ConfigOption(name: '32GB LPDDR5X', priceDelta: 0.0),
    ],
    storageOptions: [
      ConfigOption(name: '512GB SSD', priceDelta: -100.0),
      ConfigOption(name: '1TB SSD', priceDelta: 0.0),
      ConfigOption(name: '2TB SSD', priceDelta: 150.0),
    ],
    reviews: [
      LaptopReview(username: 'FieldConsultant', rating: 4.7, date: '2026-06-05', comment: 'Under 1 kg with OLED. My back thanks ASUS every single day.'),
    ],
  ),

  // ==================== LENOVO – extra ====================
  Laptop(
    id: 'lenovo_07',
    name: 'IdeaPad Pro 5 Gen 9',
    brand: 'Lenovo',
    basePrice: 1149.00,
    imageUrl: 'https://images.unsplash.com/photo-1611186871348-b1ce696e52c9?w=800&auto=format&fit=crop&q=80',
    category: 'Creators',
    rating: 4.56,
    reviewsCount: 44,
    cpu: 'AMD Ryzen 7 8845H',
    gpu: 'NVIDIA RTX 4050 (6GB)',
    ram: '16GB DDR5',
    storage: '1TB PCIe SSD',
    display: '16" 2K 2560x1600 120Hz IPS',
    battery: '80Wh – up to 10 hours',
    weight: 1.99,
    description: 'Stylish mid-range creator laptop with Ryzen 8000-series AI acceleration. Ideal for photography, light video editing, and everyday programming.',
    gamingScore: 68, codingScore: 84, productivityScore: 88, batteryScore: 76,
    cpuOptions: [ConfigOption(name: 'AMD Ryzen 7 8845H', priceDelta: 0.0)],
    gpuOptions: [
      ConfigOption(name: 'AMD Radeon 780M only', priceDelta: -150.0),
      ConfigOption(name: 'NVIDIA RTX 4050 (6GB)', priceDelta: 0.0),
    ],
    ramOptions: [
      ConfigOption(name: '16GB DDR5', priceDelta: 0.0),
      ConfigOption(name: '32GB DDR5', priceDelta: 100.0),
    ],
    storageOptions: [
      ConfigOption(name: '512GB PCIe SSD', priceDelta: -80.0),
      ConfigOption(name: '1TB PCIe SSD', priceDelta: 0.0),
    ],
    reviews: [
      LaptopReview(username: 'LightEditor', rating: 4.5, date: '2026-05-28', comment: 'Great value for photo editing. Sharp screen, GPU handles Lightroom with ease.'),
    ],
  ),
  Laptop(
    id: 'lenovo_08',
    name: 'Legion Slim 5i Gen 9',
    brand: 'Lenovo',
    basePrice: 1349.00,
    imageUrl: 'https://images.unsplash.com/photo-1504707748692-419802cf939d?w=800&auto=format&fit=crop&q=80',
    category: 'Gaming',
    rating: 4.68,
    reviewsCount: 76,
    cpu: 'Intel Core i7-14650HX',
    gpu: 'NVIDIA RTX 4060 (8GB)',
    ram: '16GB DDR5',
    storage: '1TB PCIe SSD',
    display: '16" WQXGA 2560x1600 165Hz IPS',
    battery: '80Wh – up to 7 hours',
    weight: 2.38,
    description: 'Slim gaming at a sensible price. Legion TrueStrike keyboard, excellent thermals, and a sharp 165Hz QHD display with no gaming bloat.',
    gamingScore: 82, codingScore: 82, productivityScore: 80, batteryScore: 66,
    cpuOptions: [ConfigOption(name: 'Intel Core i7-14650HX', priceDelta: 0.0)],
    gpuOptions: [
      ConfigOption(name: 'NVIDIA RTX 4060 (8GB)', priceDelta: 0.0),
      ConfigOption(name: 'NVIDIA RTX 4070 (8GB)', priceDelta: 200.0),
    ],
    ramOptions: [
      ConfigOption(name: '16GB DDR5', priceDelta: 0.0),
      ConfigOption(name: '32GB DDR5', priceDelta: 100.0),
    ],
    storageOptions: [
      ConfigOption(name: '1TB PCIe SSD', priceDelta: 0.0),
    ],
    reviews: [
      LaptopReview(username: 'SlimGameR', rating: 4.7, date: '2026-06-25', comment: 'Slim enough for lectures, powerful enough for gaming after class.'),
    ],
  ),
  Laptop(
    id: 'lenovo_09',
    name: 'Yoga Book 9i Dual Screen',
    brand: 'Lenovo',
    basePrice: 2499.00,
    imageUrl: 'https://images.unsplash.com/photo-1531297484001-80022131f5a1?w=800&auto=format&fit=crop&q=80',
    category: 'Ultra-portable',
    rating: 4.55,
    reviewsCount: 22,
    cpu: 'Intel Core Ultra 7 155U',
    gpu: 'Intel Arc Graphics',
    ram: '16GB LPDDR5X',
    storage: '1TB SSD',
    display: 'Dual 13.3" 2.8K OLED Touch',
    battery: '80Wh – up to 10 hours',
    weight: 1.34,
    description: 'Two full 13.3-inch OLED touchscreens, detachable Bluetooth keyboard that works on both screens, and an ultrathin chassis unlike anything else available.',
    gamingScore: 40, codingScore: 88, productivityScore: 95, batteryScore: 74,
    cpuOptions: [ConfigOption(name: 'Intel Core Ultra 7 155U', priceDelta: 0.0)],
    gpuOptions: [ConfigOption(name: 'Intel Arc Graphics', priceDelta: 0.0)],
    ramOptions: [ConfigOption(name: '16GB LPDDR5X', priceDelta: 0.0)],
    storageOptions: [
      ConfigOption(name: '512GB SSD', priceDelta: -100.0),
      ConfigOption(name: '1TB SSD', priceDelta: 0.0),
    ],
    reviews: [
      LaptopReview(username: 'DualDisplay', rating: 4.6, date: '2026-06-09', comment: 'Two OLED screens is incredible for comparing documents. Revolutionary.'),
    ],
  ),

  // ==================== HP – extra ====================
  Laptop(
    id: 'hp_07',
    name: 'Envy 16 OLED Creator',
    brand: 'HP',
    basePrice: 1399.00,
    imageUrl: 'https://images.unsplash.com/photo-1541807084-5c52b6b3adef?w=800&auto=format&fit=crop&q=80',
    category: 'Creators',
    rating: 4.63,
    reviewsCount: 68,
    cpu: 'Intel Core Ultra 7 155H',
    gpu: 'NVIDIA RTX 4060 (8GB)',
    ram: '16GB DDR5',
    storage: '1TB PCIe Gen4 SSD',
    display: '16" 2.8K 2880x1800 120Hz OLED',
    battery: '86Wh – up to 9 hours',
    weight: 2.14,
    description: 'Pro-grade OLED display with dedicated RTX graphics at a mid-range price. PANTONE validated color accuracy for photographers and videographers.',
    gamingScore: 68, codingScore: 87, productivityScore: 92, batteryScore: 74,
    cpuOptions: [
      ConfigOption(name: 'Intel Core Ultra 5 125H', priceDelta: -120.0),
      ConfigOption(name: 'Intel Core Ultra 7 155H', priceDelta: 0.0),
    ],
    gpuOptions: [
      ConfigOption(name: 'NVIDIA RTX 4050 (6GB)', priceDelta: -150.0),
      ConfigOption(name: 'NVIDIA RTX 4060 (8GB)', priceDelta: 0.0),
    ],
    ramOptions: [
      ConfigOption(name: '16GB DDR5', priceDelta: 0.0),
      ConfigOption(name: '32GB DDR5', priceDelta: 120.0),
    ],
    storageOptions: [
      ConfigOption(name: '1TB PCIe SSD', priceDelta: 0.0),
      ConfigOption(name: '2TB PCIe SSD', priceDelta: 100.0),
    ],
    reviews: [
      LaptopReview(username: 'PhotoCreator', rating: 4.7, date: '2026-06-30', comment: 'PANTONE validated OLED is perfect for color-critical work. Great value.'),
    ],
  ),
  Laptop(
    id: 'hp_08',
    name: 'Omen 16 RTX 4070',
    brand: 'HP',
    basePrice: 1749.00,
    imageUrl: 'https://images.unsplash.com/photo-1629429408209-1f912961dbd8?w=800&auto=format&fit=crop&q=80',
    category: 'Gaming',
    rating: 4.69,
    reviewsCount: 55,
    cpu: 'Intel Core i7-13700HX',
    gpu: 'NVIDIA RTX 4070 (8GB)',
    ram: '16GB DDR5',
    storage: '1TB NVMe SSD',
    display: '16.1" QHD 2560x1440 165Hz IPS',
    battery: '83Wh – up to 7 hours',
    weight: 2.44,
    description: 'Solid mid-range gaming with QHD 165Hz display and RTX 4070. Omen Command Center lets you push performance or extend battery life as needed.',
    gamingScore: 88, codingScore: 85, productivityScore: 82, batteryScore: 64,
    cpuOptions: [ConfigOption(name: 'Intel Core i7-13700HX', priceDelta: 0.0)],
    gpuOptions: [
      ConfigOption(name: 'NVIDIA RTX 4060 (8GB)', priceDelta: -200.0),
      ConfigOption(name: 'NVIDIA RTX 4070 (8GB)', priceDelta: 0.0),
    ],
    ramOptions: [
      ConfigOption(name: '16GB DDR5', priceDelta: 0.0),
      ConfigOption(name: '32GB DDR5', priceDelta: 100.0),
    ],
    storageOptions: [
      ConfigOption(name: '1TB NVMe SSD', priceDelta: 0.0),
      ConfigOption(name: '2TB NVMe SSD', priceDelta: 100.0),
    ],
    reviews: [
      LaptopReview(username: 'MidRangeGamer', rating: 4.7, date: '2026-06-14', comment: 'QHD at 165Hz feels amazing. No other laptop at this price has this display.'),
    ],
  ),
  Laptop(
    id: 'hp_09',
    name: 'EliteBook 860 G11',
    brand: 'HP',
    basePrice: 1299.00,
    imageUrl: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=800&auto=format&fit=crop&q=80',
    category: 'Business',
    rating: 4.59,
    reviewsCount: 34,
    cpu: 'Intel Core Ultra 5 135U',
    gpu: 'Intel Arc Graphics',
    ram: '16GB LPDDR5X',
    storage: '512GB PCIe SSD',
    display: '16" WUXGA 1920x1200 IPS Anti-Glare',
    battery: '76Wh – up to 16 hours',
    weight: 1.78,
    description: 'Reliable business workhorse with outstanding battery life. HP Wolf Security built-in, Intel vPro manageability, and premium build at a business-friendly price point.',
    gamingScore: 38, codingScore: 83, productivityScore: 93, batteryScore: 93,
    cpuOptions: [
      ConfigOption(name: 'Intel Core Ultra 5 135U', priceDelta: 0.0),
      ConfigOption(name: 'Intel Core Ultra 7 165U', priceDelta: 150.0),
    ],
    gpuOptions: [ConfigOption(name: 'Intel Arc Graphics', priceDelta: 0.0)],
    ramOptions: [
      ConfigOption(name: '16GB LPDDR5X', priceDelta: 0.0),
      ConfigOption(name: '32GB LPDDR5X', priceDelta: 100.0),
    ],
    storageOptions: [
      ConfigOption(name: '512GB PCIe SSD', priceDelta: 0.0),
      ConfigOption(name: '1TB PCIe SSD', priceDelta: 80.0),
    ],
    reviews: [
      LaptopReview(username: 'ITAdmin', rating: 4.6, date: '2026-05-10', comment: 'HP Wolf Security is top-notch. Fleet favorite for our company rollout.'),
    ],
  ),

  // ==================== DELL – extra ====================
  Laptop(
    id: 'dell_07',
    name: 'G16 Gaming 7630',
    brand: 'Dell',
    basePrice: 1299.00,
    imageUrl: 'https://images.unsplash.com/photo-1593642632823-8f785ba67e45?w=800&auto=format&fit=crop&q=80',
    category: 'Gaming',
    rating: 4.55,
    reviewsCount: 60,
    cpu: 'Intel Core i7-13650HX',
    gpu: 'NVIDIA RTX 4060 (8GB)',
    ram: '16GB DDR5',
    storage: '512GB NVMe SSD',
    display: '16" QHD+ 2560x1600 165Hz IPS',
    battery: '86Wh – up to 7 hours',
    weight: 2.84,
    description: 'Dell\'s accessible gaming laptop with QHD+ display and solid RTX 4060 performance. Loud speakers and plenty of connectivity for a complete gaming setup.',
    gamingScore: 80, codingScore: 78, productivityScore: 76, batteryScore: 60,
    cpuOptions: [ConfigOption(name: 'Intel Core i7-13650HX', priceDelta: 0.0)],
    gpuOptions: [
      ConfigOption(name: 'NVIDIA RTX 4060 (8GB)', priceDelta: 0.0),
      ConfigOption(name: 'NVIDIA RTX 4070 (8GB)', priceDelta: 200.0),
    ],
    ramOptions: [
      ConfigOption(name: '16GB DDR5', priceDelta: 0.0),
      ConfigOption(name: '32GB DDR5', priceDelta: 100.0),
    ],
    storageOptions: [
      ConfigOption(name: '512GB NVMe SSD', priceDelta: 0.0),
      ConfigOption(name: '1TB NVMe SSD', priceDelta: 70.0),
    ],
    reviews: [
      LaptopReview(username: 'G16Fan', rating: 4.5, date: '2026-05-15', comment: 'QHD display at this price is a steal. Great entry gaming laptop.'),
    ],
  ),
  Laptop(
    id: 'dell_08',
    name: 'XPS 13 Plus OLED',
    brand: 'Dell',
    basePrice: 1799.00,
    imageUrl: 'https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?w=800&auto=format&fit=crop&q=80',
    category: 'Ultra-portable',
    rating: 4.76,
    reviewsCount: 92,
    cpu: 'Intel Core Ultra 7 155H',
    gpu: 'Intel Arc Graphics',
    ram: '32GB LPDDR5X',
    storage: '1TB PCIe SSD',
    display: '13.4" 3.5K 2880x1800 OLED Touch',
    battery: '55Wh – up to 10 hours',
    weight: 1.26,
    description: 'The most futuristic ultrabook design. Invisible haptic keyboard, edge-to-edge glass trackpad, and a stunning 3.5K OLED in a chassis that looks straight out of sci-fi.',
    gamingScore: 45, codingScore: 88, productivityScore: 92, batteryScore: 80,
    cpuOptions: [ConfigOption(name: 'Intel Core Ultra 7 155H', priceDelta: 0.0)],
    gpuOptions: [ConfigOption(name: 'Intel Arc Graphics', priceDelta: 0.0)],
    ramOptions: [
      ConfigOption(name: '16GB LPDDR5X', priceDelta: -100.0),
      ConfigOption(name: '32GB LPDDR5X', priceDelta: 0.0),
    ],
    storageOptions: [
      ConfigOption(name: '512GB PCIe SSD', priceDelta: -100.0),
      ConfigOption(name: '1TB PCIe SSD', priceDelta: 0.0),
      ConfigOption(name: '2TB PCIe SSD', priceDelta: 200.0),
    ],
    reviews: [
      LaptopReview(username: 'DesignAesthetic', rating: 4.8, date: '2026-07-02', comment: 'Looks like it is from 2040. Invisible keyboard design is jaw-dropping.'),
    ],
  ),
  Laptop(
    id: 'dell_09',
    name: 'Latitude 9450 2-in-1',
    brand: 'Dell',
    basePrice: 1999.00,
    imageUrl: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=800&auto=format&fit=crop&q=80',
    category: 'Business',
    rating: 4.70,
    reviewsCount: 28,
    cpu: 'Intel Core Ultra 7 164U',
    gpu: 'Intel Arc Graphics',
    ram: '32GB LPDDR5X',
    storage: '1TB SSD',
    display: '14" 2.8K 2880x1800 OLED Touch 2-in-1',
    battery: '65Wh – up to 14 hours',
    weight: 1.44,
    description: 'Dell flagship business 2-in-1 with Copilot+ AI key, stunning OLED touchscreen, built-in privacy shutter, and enterprise Dell ProSupport management.',
    gamingScore: 40, codingScore: 86, productivityScore: 96, batteryScore: 88,
    cpuOptions: [ConfigOption(name: 'Intel Core Ultra 7 164U', priceDelta: 0.0)],
    gpuOptions: [ConfigOption(name: 'Intel Arc Graphics', priceDelta: 0.0)],
    ramOptions: [
      ConfigOption(name: '16GB LPDDR5X', priceDelta: -150.0),
      ConfigOption(name: '32GB LPDDR5X', priceDelta: 0.0),
    ],
    storageOptions: [
      ConfigOption(name: '512GB SSD', priceDelta: -100.0),
      ConfigOption(name: '1TB SSD', priceDelta: 0.0),
      ConfigOption(name: '2TB SSD', priceDelta: 200.0),
    ],
    reviews: [
      LaptopReview(username: 'CxO', rating: 4.7, date: '2026-06-22', comment: 'OLED in tent mode for presentations is spectacular. Perfect for business travel.'),
    ],
  ),
];

